'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmWidth() As Integer
            Get
                Return CType(Me("ifrmWidth"),Integer)
            End Get
            Set
                Me("ifrmWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmHeight() As Integer
            Get
                Return CType(Me("ifrmHeight"),Integer)
            End Get
            Set
                Me("ifrmHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frm_Location() As String
            Get
                Return CType(Me("frm_Location"),String)
            End Get
            Set
                Me("frm_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LV_1_Size() As String
            Get
                Return CType(Me("LV_1_Size"),String)
            End Get
            Set
                Me("LV_1_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Filename4CSV() As String
            Get
                Return CType(Me("Filename4CSV"),String)
            End Get
            Set
                Me("Filename4CSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrennzeichenCSV() As String
            Get
                Return CType(Me("TrennzeichenCSV"),String)
            End Get
            Set
                Me("TrennzeichenCSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DarstellungszeichenCSV() As String
            Get
                Return CType(Me("DarstellungszeichenCSV"),String)
            End Get
            Set
                Me("DarstellungszeichenCSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Rec_KDNr_Size() As String
            Get
                Return CType(Me("Rec_KDNr_Size"),String)
            End Get
            Set
                Me("Rec_KDNr_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LV_2_Size() As String
            Get
                Return CType(Me("LV_2_Size"),String)
            End Get
            Set
                Me("LV_2_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_1() As Boolean
            Get
                Return CType(Me("bOpen_P_1_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_2() As Boolean
            Get
                Return CType(Me("bOpen_P_1_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_3() As Boolean
            Get
                Return CType(Me("bOpen_P_1_3"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KDNr, Firma1, KDFirma2, KDFirma3, KDPLZ, KDOrt, KDPostfach, KDLand, KDTelefon, KD"& _ 
            "Telefax, KDStrasse, KDTelefax, KDStrasse, KDAllFiliale, Anrede, Nachname, Vornam"& _ 
            "e, AnredeForm, ZHDAbt, ZHDPos, ZHDBerater")>  _
        Public Property ExportFields() As String
            Get
                Return CType(Me("ExportFields"),String)
            End Get
            Set
                Me("ExportFields") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_1() As Boolean
            Get
                Return CType(Me("bOpen_P_2_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_2() As Boolean
            Get
                Return CType(Me("bOpen_P_2_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_3() As Boolean
            Get
                Return CType(Me("bOpen_P_2_3"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_4() As Boolean
            Get
                Return CType(Me("bOpen_P_2_4"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_5() As Boolean
            Get
                Return CType(Me("bOpen_P_2_5"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_4_2() As Boolean
            Get
                Return CType(Me("bOpen_P_4_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_4_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_3_1() As Boolean
            Get
                Return CType(Me("bOpen_P_3_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_3_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_3_2() As Boolean
            Get
                Return CType(Me("bOpen_P_3_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_3_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_3_3() As Boolean
            Get
                Return CType(Me("bOpen_P_3_3"),Boolean)
            End Get
            Set
                Me("bOpen_P_3_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortBez() As String
            Get
                Return CType(Me("SortBez"),String)
            End Get
            Set
                Me("SortBez") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLVWidth() As Integer
            Get
                Return CType(Me("ifrmLVWidth"),Integer)
            End Get
            Set
                Me("ifrmLVWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLVHeight() As Integer
            Get
                Return CType(Me("ifrmLVHeight"),Integer)
            End Get
            Set
                Me("ifrmLVHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frm_LVLocation() As String
            Get
                Return CType(Me("frm_LVLocation"),String)
            End Get
            Set
                Me("frm_LVLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_KDNr() As String
            Get
                Return CType(Me("bShowColumn_KDNr"),String)
            End Get
            Set
                Me("bShowColumn_KDNr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_Customername() As String
            Get
                Return CType(Me("bShowColumn_Customername"),String)
            End Get
            Set
                Me("bShowColumn_Customername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customername2() As String
            Get
                Return CType(Me("bShowColumn_customername2"),String)
            End Get
            Set
                Me("bShowColumn_customername2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customername3() As String
            Get
                Return CType(Me("bShowColumn_customername3"),String)
            End Get
            Set
                Me("bShowColumn_customername3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customerstreet() As String
            Get
                Return CType(Me("bShowColumn_customerstreet"),String)
            End Get
            Set
                Me("bShowColumn_customerstreet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customeraddress() As String
            Get
                Return CType(Me("bShowColumn_customeraddress"),String)
            End Get
            Set
                Me("bShowColumn_customeraddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customerpostcode() As String
            Get
                Return CType(Me("bShowColumn_customerpostcode"),String)
            End Get
            Set
                Me("bShowColumn_customerpostcode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customercity() As String
            Get
                Return CType(Me("bShowColumn_customercity"),String)
            End Get
            Set
                Me("bShowColumn_customercity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customerbox() As String
            Get
                Return CType(Me("bShowColumn_customerbox"),String)
            End Get
            Set
                Me("bShowColumn_customerbox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customertelefon() As String
            Get
                Return CType(Me("bShowColumn_customertelefon"),String)
            End Get
            Set
                Me("bShowColumn_customertelefon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customertelefax() As String
            Get
                Return CType(Me("bShowColumn_customertelefax"),String)
            End Get
            Set
                Me("bShowColumn_customertelefax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customeremail() As String
            Get
                Return CType(Me("bShowColumn_customeremail"),String)
            End Get
            Set
                Me("bShowColumn_customeremail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_kreditlimite() As String
            Get
                Return CType(Me("bShowColumn_kreditlimite"),String)
            End Get
            Set
                Me("bShowColumn_kreditlimite") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_kreditlimite2() As String
            Get
                Return CType(Me("bShowColumn_kreditlimite2"),String)
            End Get
            Set
                Me("bShowColumn_kreditlimite2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_kreditab() As String
            Get
                Return CType(Me("bShowColumn_kreditab"),String)
            End Get
            Set
                Me("bShowColumn_kreditab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_kreditbis() As String
            Get
                Return CType(Me("bShowColumn_kreditbis"),String)
            End Get
            Set
                Me("bShowColumn_kreditbis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_kreditwarning() As String
            Get
                Return CType(Me("bShowColumn_kreditwarning"),String)
            End Get
            Set
                Me("bShowColumn_kreditwarning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customerumsatzmin() As String
            Get
                Return CType(Me("bShowColumn_customerumsatzmin"),String)
            End Get
            Set
                Me("bShowColumn_customerumsatzmin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsiblefullname() As String
            Get
                Return CType(Me("bShowColumn_cresponsiblefullname"),String)
            End Get
            Set
                Me("bShowColumn_cresponsiblefullname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibletelefon() As String
            Get
                Return CType(Me("bShowColumn_cresponsibletelefon"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibletelefon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibletelefax() As String
            Get
                Return CType(Me("bShowColumn_cresponsibletelefax"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibletelefax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsiblemobile() As String
            Get
                Return CType(Me("bShowColumn_cresponsiblemobile"),String)
            End Get
            Set
                Me("bShowColumn_cresponsiblemobile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibleemail() As String
            Get
                Return CType(Me("bShowColumn_cresponsibleemail"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibleemail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibleabteilung() As String
            Get
                Return CType(Me("bShowColumn_cresponsibleabteilung"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibleabteilung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibleposition() As String
            Get
                Return CType(Me("bShowColumn_cresponsibleposition"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibleposition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_customeradvisor() As String
            Get
                Return CType(Me("bShowColumn_customeradvisor"),String)
            End Get
            Set
                Me("bShowColumn_customeradvisor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsibleadvisor() As String
            Get
                Return CType(Me("bShowColumn_cresponsibleadvisor"),String)
            End Get
            Set
                Me("bShowColumn_cresponsibleadvisor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsiblefstate() As String
            Get
                Return CType(Me("bShowColumn_cresponsiblefstate"),String)
            End Get
            Set
                Me("bShowColumn_cresponsiblefstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_cresponsiblesstate() As String
            Get
                Return CType(Me("bShowColumn_cresponsiblesstate"),String)
            End Get
            Set
                Me("bShowColumn_cresponsiblesstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frmLibraryInfo_Location() As String
            Get
                Return CType(Me("frmLibraryInfo_Location"),String)
            End Get
            Set
                Me("frmLibraryInfo_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLibraryInfoWidth() As Integer
            Get
                Return CType(Me("ifrmLibraryInfoWidth"),Integer)
            End Get
            Set
                Me("ifrmLibraryInfoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLibraryInfoHeight() As Integer
            Get
                Return CType(Me("ifrmLibraryInfoHeight"),Integer)
            End Get
            Set
                Me("ifrmLibraryInfoHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frmLocation_SearchRec() As String
            Get
                Return CType(Me("frmLocation_SearchRec"),String)
            End Get
            Set
                Me("frmLocation_SearchRec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property iSearchRec_Width() As Integer
            Get
                Return CType(Me("iSearchRec_Width"),Integer)
            End Get
            Set
                Me("iSearchRec_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property iSearchRec_Height() As Integer
            Get
                Return CType(Me("iSearchRec_Height"),Integer)
            End Get
            Set
                Me("iSearchRec_Height") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SPKDSearch.My.MySettings
            Get
                Return Global.SPKDSearch.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
