'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property customermng_ifrmWidth() As Integer
            Get
                Return CType(Me("customermng_ifrmWidth"),Integer)
            End Get
            Set
                Me("customermng_ifrmWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property customermng_ifrmHeight() As Integer
            Get
                Return CType(Me("customermng_ifrmHeight"),Integer)
            End Get
            Set
                Me("customermng_ifrmHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property customermng_frmLocation() As String
            Get
                Return CType(Me("customermng_frmLocation"),String)
            End Get
            Set
                Me("customermng_frmLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property customermng_iSccMainPos() As Integer
            Get
                Return CType(Me("customermng_iSccMainPos"),Integer)
            End Get
            Set
                Me("customermng_iSccMainPos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property customermng_popup_KeywordsSize() As String
            Get
                Return CType(Me("customermng_popup_KeywordsSize"),String)
            End Get
            Set
                Me("customermng_popup_KeywordsSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property customermng_popup_GAVSize() As String
            Get
                Return CType(Me("customermng_popup_GAVSize"),String)
            End Get
            Set
                Me("customermng_popup_GAVSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property customermng_contactSearchExcludePhone() As Boolean
            Get
                Return CType(Me("customermng_contactSearchExcludePhone"),Boolean)
            End Get
            Set
                Me("customermng_contactSearchExcludePhone") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property customermng_contactSearchExcludeMail() As Boolean
            Get
                Return CType(Me("customermng_contactSearchExcludeMail"),Boolean)
            End Get
            Set
                Me("customermng_contactSearchExcludeMail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property customermng_contactSearchExcludeOffered() As Boolean
            Get
                Return CType(Me("customermng_contactSearchExcludeOffered"),Boolean)
            End Get
            Set
                Me("customermng_contactSearchExcludeOffered") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property customermng_contactSearchExcludeSMS() As Boolean
            Get
                Return CType(Me("customermng_contactSearchExcludeSMS"),Boolean)
            End Get
            Set
                Me("customermng_contactSearchExcludeSMS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property customermng_properties_ifrmWidth() As Integer
            Get
                Return CType(Me("customermng_properties_ifrmWidth"),Integer)
            End Get
            Set
                Me("customermng_properties_ifrmWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property customermng_properties_ifrmHeight() As Integer
            Get
                Return CType(Me("customermng_properties_ifrmHeight"),Integer)
            End Get
            Set
                Me("customermng_properties_ifrmHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property customermng_properties_frmLocation() As String
            Get
                Return CType(Me("customermng_properties_frmLocation"),String)
            End Get
            Set
                Me("customermng_properties_frmLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property newcustomermng_ifrmWidth() As Integer
            Get
                Return CType(Me("newcustomermng_ifrmWidth"),Integer)
            End Get
            Set
                Me("newcustomermng_ifrmWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property newcustomermng_ifrmHeight() As Integer
            Get
                Return CType(Me("newcustomermng_ifrmHeight"),Integer)
            End Get
            Set
                Me("newcustomermng_ifrmHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property newcustomermng_frmLocation() As String
            Get
                Return CType(Me("newcustomermng_frmLocation"),String)
            End Get
            Set
                Me("newcustomermng_frmLocation") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SP.KD.CustomerMng.My.MySettings
            Get
                Return Global.SP.KD.CustomerMng.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
