'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EmployeeTaxInfoWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TaxDataDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TaxDataDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField() As EmployeeTaxInfoWebService.TaxDataItemDTO
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Data() As EmployeeTaxInfoWebService.TaxDataItemDTO()
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TaxDataItemDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TaxDataItemDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KantonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GruppeField As String
        
        Private KinderField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KirchensteuerField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Kanton() As String
            Get
                Return Me.KantonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KantonField, value) <> true) Then
                    Me.KantonField = value
                    Me.RaisePropertyChanged("Kanton")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Gruppe() As String
            Get
                Return Me.GruppeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GruppeField, value) <> true) Then
                    Me.GruppeField = value
                    Me.RaisePropertyChanged("Gruppe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Kinder() As Short
            Get
                Return Me.KinderField
            End Get
            Set
                If (Me.KinderField.Equals(value) <> true) Then
                    Me.KinderField = value
                    Me.RaisePropertyChanged("Kinder")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Kirchensteuer() As String
            Get
                Return Me.KirchensteuerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KirchensteuerField, value) <> true) Then
                    Me.KirchensteuerField = value
                    Me.RaisePropertyChanged("Kirchensteuer")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QstDataDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class QstDataDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Mindest_AbzugField As Decimal
        
        Private Steuer_ProzField As Decimal
        
        Private EinkommenField As Decimal
        
        Private SchrittField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Mindest_Abzug() As Decimal
            Get
                Return Me.Mindest_AbzugField
            End Get
            Set
                If (Me.Mindest_AbzugField.Equals(value) <> true) Then
                    Me.Mindest_AbzugField = value
                    Me.RaisePropertyChanged("Mindest_Abzug")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Steuer_Proz() As Decimal
            Get
                Return Me.Steuer_ProzField
            End Get
            Set
                If (Me.Steuer_ProzField.Equals(value) <> true) Then
                    Me.Steuer_ProzField = value
                    Me.RaisePropertyChanged("Steuer_Proz")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Einkommen() As Decimal
            Get
                Return Me.EinkommenField
            End Get
            Set
                If (Me.EinkommenField.Equals(value) <> true) Then
                    Me.EinkommenField = value
                    Me.RaisePropertyChanged("Einkommen")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Schritt() As Decimal
            Get
                Return Me.SchrittField
            End Get
            Set
                If (Me.SchrittField.Equals(value) <> true) Then
                    Me.SchrittField = value
                    Me.RaisePropertyChanged("Schritt")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QstDataAllowedDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class QstDataAllowedDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IsQstDataAllowedField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property IsQstDataAllowed() As Boolean
            Get
                Return Me.IsQstDataAllowedField
            End Get
            Set
                If (Me.IsQstDataAllowedField.Equals(value) <> true) Then
                    Me.IsQstDataAllowedField = value
                    Me.RaisePropertyChanged("IsQstDataAllowed")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChildEducationDataDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ChildEducationDataDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        Private MDYearField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FAK_KantonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fak_NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fak_ZHDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fak_PostfachField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fak_StrasseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fak_PLZOrtField As String
        
        Private YMinLohnField As System.Nullable(Of Decimal)
        
        Private Ki1_MonthField As System.Nullable(Of Decimal)
        
        Private Ki2_MonthField As System.Nullable(Of Decimal)
        
        Private Au1_MonthField As System.Nullable(Of Decimal)
        
        Private Ki1_StdField As System.Nullable(Of Decimal)
        
        Private Ki2_StdField As System.Nullable(Of Decimal)
        
        Private Ki1_DayField As System.Nullable(Of Decimal)
        
        Private Ki2_DayField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChangeKiInField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChangeKiIn_2Field As String
        
        Private Au1_StdField As System.Nullable(Of Decimal)
        
        Private Au2_StdField As System.Nullable(Of Decimal)
        
        Private Au1_DayField As System.Nullable(Of Decimal)
        
        Private Au2_DayField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChangeAuInField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChangeAuIn_2Field As String
        
        Private CreatedOnField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedFromField As String
        
        Private ChangedOnField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChangedFromField As String
        
        Private Ki1_FakMaxField As System.Nullable(Of Decimal)
        
        Private Ki2_FakMaxField As System.Nullable(Of Decimal)
        
        Private Fak_ProzField As System.Nullable(Of Decimal)
        
        Private Geb_ZulageField As System.Nullable(Of Decimal)
        
        Private Ado_ZulageField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Bemerkung_1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Bemerkung_2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Bemerkung_3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Bemerkung_4Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property MDYear() As Integer
            Get
                Return Me.MDYearField
            End Get
            Set
                If (Me.MDYearField.Equals(value) <> true) Then
                    Me.MDYearField = value
                    Me.RaisePropertyChanged("MDYear")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property FAK_Kanton() As String
            Get
                Return Me.FAK_KantonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FAK_KantonField, value) <> true) Then
                    Me.FAK_KantonField = value
                    Me.RaisePropertyChanged("FAK_Kanton")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Fak_Name() As String
            Get
                Return Me.Fak_NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fak_NameField, value) <> true) Then
                    Me.Fak_NameField = value
                    Me.RaisePropertyChanged("Fak_Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Fak_ZHD() As String
            Get
                Return Me.Fak_ZHDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fak_ZHDField, value) <> true) Then
                    Me.Fak_ZHDField = value
                    Me.RaisePropertyChanged("Fak_ZHD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Fak_Postfach() As String
            Get
                Return Me.Fak_PostfachField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fak_PostfachField, value) <> true) Then
                    Me.Fak_PostfachField = value
                    Me.RaisePropertyChanged("Fak_Postfach")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Fak_Strasse() As String
            Get
                Return Me.Fak_StrasseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fak_StrasseField, value) <> true) Then
                    Me.Fak_StrasseField = value
                    Me.RaisePropertyChanged("Fak_Strasse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Fak_PLZOrt() As String
            Get
                Return Me.Fak_PLZOrtField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Fak_PLZOrtField, value) <> true) Then
                    Me.Fak_PLZOrtField = value
                    Me.RaisePropertyChanged("Fak_PLZOrt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property YMinLohn() As System.Nullable(Of Decimal)
            Get
                Return Me.YMinLohnField
            End Get
            Set
                If (Me.YMinLohnField.Equals(value) <> true) Then
                    Me.YMinLohnField = value
                    Me.RaisePropertyChanged("YMinLohn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property Ki1_Month() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki1_MonthField
            End Get
            Set
                If (Me.Ki1_MonthField.Equals(value) <> true) Then
                    Me.Ki1_MonthField = value
                    Me.RaisePropertyChanged("Ki1_Month")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Public Property Ki2_Month() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki2_MonthField
            End Get
            Set
                If (Me.Ki2_MonthField.Equals(value) <> true) Then
                    Me.Ki2_MonthField = value
                    Me.RaisePropertyChanged("Ki2_Month")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Public Property Au1_Month() As System.Nullable(Of Decimal)
            Get
                Return Me.Au1_MonthField
            End Get
            Set
                If (Me.Au1_MonthField.Equals(value) <> true) Then
                    Me.Au1_MonthField = value
                    Me.RaisePropertyChanged("Au1_Month")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=12)>  _
        Public Property Ki1_Std() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki1_StdField
            End Get
            Set
                If (Me.Ki1_StdField.Equals(value) <> true) Then
                    Me.Ki1_StdField = value
                    Me.RaisePropertyChanged("Ki1_Std")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property Ki2_Std() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki2_StdField
            End Get
            Set
                If (Me.Ki2_StdField.Equals(value) <> true) Then
                    Me.Ki2_StdField = value
                    Me.RaisePropertyChanged("Ki2_Std")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=14)>  _
        Public Property Ki1_Day() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki1_DayField
            End Get
            Set
                If (Me.Ki1_DayField.Equals(value) <> true) Then
                    Me.Ki1_DayField = value
                    Me.RaisePropertyChanged("Ki1_Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=15)>  _
        Public Property Ki2_Day() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki2_DayField
            End Get
            Set
                If (Me.Ki2_DayField.Equals(value) <> true) Then
                    Me.Ki2_DayField = value
                    Me.RaisePropertyChanged("Ki2_Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property ChangeKiIn() As String
            Get
                Return Me.ChangeKiInField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChangeKiInField, value) <> true) Then
                    Me.ChangeKiInField = value
                    Me.RaisePropertyChanged("ChangeKiIn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property ChangeKiIn_2() As String
            Get
                Return Me.ChangeKiIn_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChangeKiIn_2Field, value) <> true) Then
                    Me.ChangeKiIn_2Field = value
                    Me.RaisePropertyChanged("ChangeKiIn_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=18)>  _
        Public Property Au1_Std() As System.Nullable(Of Decimal)
            Get
                Return Me.Au1_StdField
            End Get
            Set
                If (Me.Au1_StdField.Equals(value) <> true) Then
                    Me.Au1_StdField = value
                    Me.RaisePropertyChanged("Au1_Std")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=19)>  _
        Public Property Au2_Std() As System.Nullable(Of Decimal)
            Get
                Return Me.Au2_StdField
            End Get
            Set
                If (Me.Au2_StdField.Equals(value) <> true) Then
                    Me.Au2_StdField = value
                    Me.RaisePropertyChanged("Au2_Std")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=20)>  _
        Public Property Au1_Day() As System.Nullable(Of Decimal)
            Get
                Return Me.Au1_DayField
            End Get
            Set
                If (Me.Au1_DayField.Equals(value) <> true) Then
                    Me.Au1_DayField = value
                    Me.RaisePropertyChanged("Au1_Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=21)>  _
        Public Property Au2_Day() As System.Nullable(Of Decimal)
            Get
                Return Me.Au2_DayField
            End Get
            Set
                If (Me.Au2_DayField.Equals(value) <> true) Then
                    Me.Au2_DayField = value
                    Me.RaisePropertyChanged("Au2_Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property ChangeAuIn() As String
            Get
                Return Me.ChangeAuInField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChangeAuInField, value) <> true) Then
                    Me.ChangeAuInField = value
                    Me.RaisePropertyChanged("ChangeAuIn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property ChangeAuIn_2() As String
            Get
                Return Me.ChangeAuIn_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChangeAuIn_2Field, value) <> true) Then
                    Me.ChangeAuIn_2Field = value
                    Me.RaisePropertyChanged("ChangeAuIn_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=24)>  _
        Public Property CreatedOn() As System.Nullable(Of Date)
            Get
                Return Me.CreatedOnField
            End Get
            Set
                If (Me.CreatedOnField.Equals(value) <> true) Then
                    Me.CreatedOnField = value
                    Me.RaisePropertyChanged("CreatedOn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=25)>  _
        Public Property CreatedFrom() As String
            Get
                Return Me.CreatedFromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedFromField, value) <> true) Then
                    Me.CreatedFromField = value
                    Me.RaisePropertyChanged("CreatedFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=26)>  _
        Public Property ChangedOn() As System.Nullable(Of Date)
            Get
                Return Me.ChangedOnField
            End Get
            Set
                If (Me.ChangedOnField.Equals(value) <> true) Then
                    Me.ChangedOnField = value
                    Me.RaisePropertyChanged("ChangedOn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=27)>  _
        Public Property ChangedFrom() As String
            Get
                Return Me.ChangedFromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChangedFromField, value) <> true) Then
                    Me.ChangedFromField = value
                    Me.RaisePropertyChanged("ChangedFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=28)>  _
        Public Property Ki1_FakMax() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki1_FakMaxField
            End Get
            Set
                If (Me.Ki1_FakMaxField.Equals(value) <> true) Then
                    Me.Ki1_FakMaxField = value
                    Me.RaisePropertyChanged("Ki1_FakMax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=29)>  _
        Public Property Ki2_FakMax() As System.Nullable(Of Decimal)
            Get
                Return Me.Ki2_FakMaxField
            End Get
            Set
                If (Me.Ki2_FakMaxField.Equals(value) <> true) Then
                    Me.Ki2_FakMaxField = value
                    Me.RaisePropertyChanged("Ki2_FakMax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=30)>  _
        Public Property Fak_Proz() As System.Nullable(Of Decimal)
            Get
                Return Me.Fak_ProzField
            End Get
            Set
                If (Me.Fak_ProzField.Equals(value) <> true) Then
                    Me.Fak_ProzField = value
                    Me.RaisePropertyChanged("Fak_Proz")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=31)>  _
        Public Property Geb_Zulage() As System.Nullable(Of Decimal)
            Get
                Return Me.Geb_ZulageField
            End Get
            Set
                If (Me.Geb_ZulageField.Equals(value) <> true) Then
                    Me.Geb_ZulageField = value
                    Me.RaisePropertyChanged("Geb_Zulage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=32)>  _
        Public Property Ado_Zulage() As System.Nullable(Of Decimal)
            Get
                Return Me.Ado_ZulageField
            End Get
            Set
                If (Me.Ado_ZulageField.Equals(value) <> true) Then
                    Me.Ado_ZulageField = value
                    Me.RaisePropertyChanged("Ado_Zulage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=33)>  _
        Public Property Bemerkung_1() As String
            Get
                Return Me.Bemerkung_1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Bemerkung_1Field, value) <> true) Then
                    Me.Bemerkung_1Field = value
                    Me.RaisePropertyChanged("Bemerkung_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=34)>  _
        Public Property Bemerkung_2() As String
            Get
                Return Me.Bemerkung_2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Bemerkung_2Field, value) <> true) Then
                    Me.Bemerkung_2Field = value
                    Me.RaisePropertyChanged("Bemerkung_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=35)>  _
        Public Property Bemerkung_3() As String
            Get
                Return Me.Bemerkung_3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Bemerkung_3Field, value) <> true) Then
                    Me.Bemerkung_3Field = value
                    Me.RaisePropertyChanged("Bemerkung_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=36)>  _
        Public Property Bemerkung_4() As String
            Get
                Return Me.Bemerkung_4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Bemerkung_4Field, value) <> true) Then
                    Me.Bemerkung_4Field = value
                    Me.RaisePropertyChanged("Bemerkung_4")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", ConfigurationName:="EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap")>  _
    Public Interface SPEmployeeTaxInfoServiceSoap
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname canton aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/GetTaxInf"& _ 
            "o", ReplyAction:="*")>  _
        Function GetTaxInfo(ByVal request As EmployeeTaxInfoWebService.GetTaxInfoRequest) As EmployeeTaxInfoWebService.GetTaxInfoResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/LoadTaxIn"& _ 
            "foData", ReplyAction:="*")>  _
        Function LoadTaxInfoData(ByVal request As EmployeeTaxInfoWebService.LoadTaxInfoDataRequest) As EmployeeTaxInfoWebService.LoadTaxInfoDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/GetQstDat"& _ 
            "a", ReplyAction:="*")>  _
        Function GetQstData(ByVal request As EmployeeTaxInfoWebService.GetQstDataRequest) As EmployeeTaxInfoWebService.GetQstDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/LoadAllow"& _ 
            "edQstCode", ReplyAction:="*")>  _
        Function LoadAllowedQstCode(ByVal request As EmployeeTaxInfoWebService.LoadAllowedQstCodeRequest) As EmployeeTaxInfoWebService.LoadAllowedQstCodeResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname canton aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/GetIsAllo"& _ 
            "wedQstCode", ReplyAction:="*")>  _
        Function GetIsAllowedQstCode(ByVal request As EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequest) As EmployeeTaxInfoWebService.GetIsAllowedQstCodeResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/LoadChild"& _ 
            "EducationData", ReplyAction:="*")>  _
        Function LoadChildEducationData(ByVal request As EmployeeTaxInfoWebService.LoadChildEducationDataRequest) As EmployeeTaxInfoWebService.LoadChildEducationDataResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaxInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaxInfo", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetTaxInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetTaxInfoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetTaxInfoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public year As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal canton As String, ByVal year As Integer)
            MyBase.New
            Me.canton = canton
            Me.year = year
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTaxInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTaxInfoResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetTaxInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetTaxInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetTaxInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTaxInfoResult As EmployeeTaxInfoWebService.TaxDataDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTaxInfoResult As EmployeeTaxInfoWebService.TaxDataDTO)
            MyBase.New
            Me.GetTaxInfoResult = GetTaxInfoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadTaxInfoDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadTaxInfoData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadTaxInfoDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadTaxInfoDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadTaxInfoDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public year As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal canton As String, ByVal year As Integer)
            MyBase.New
            Me.customerID = customerID
            Me.canton = canton
            Me.year = year
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadTaxInfoDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadTaxInfoDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadTaxInfoDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadTaxInfoDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadTaxInfoDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadTaxInfoDataResult As EmployeeTaxInfoWebService.TaxDataDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadTaxInfoDataResult As EmployeeTaxInfoWebService.TaxDataDTO)
            MyBase.New
            Me.LoadTaxInfoDataResult = LoadTaxInfoDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetQstDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetQstData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetQstDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetQstDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetQstDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public year As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public einkommen As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public childern As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public qstGroup As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public kirchsteuer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public geschlecht As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String)
            MyBase.New
            Me.customerID = customerID
            Me.canton = canton
            Me.year = year
            Me.einkommen = einkommen
            Me.childern = childern
            Me.qstGroup = qstGroup
            Me.kirchsteuer = kirchsteuer
            Me.geschlecht = geschlecht
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetQstDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetQstDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetQstDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetQstDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetQstDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetQstDataResult() As EmployeeTaxInfoWebService.QstDataDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetQstDataResult() As EmployeeTaxInfoWebService.QstDataDTO)
            MyBase.New
            Me.GetQstDataResult = GetQstDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAllowedQstCodeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAllowedQstCode", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadAllowedQstCodeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadAllowedQstCodeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadAllowedQstCodeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public year As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public einkommen As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public childern As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public qstGroup As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public kirchsteuer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public geschlecht As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String)
            MyBase.New
            Me.customerID = customerID
            Me.canton = canton
            Me.year = year
            Me.einkommen = einkommen
            Me.childern = childern
            Me.qstGroup = qstGroup
            Me.kirchsteuer = kirchsteuer
            Me.geschlecht = geschlecht
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAllowedQstCodeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAllowedQstCodeResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadAllowedQstCodeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadAllowedQstCodeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadAllowedQstCodeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadAllowedQstCodeResult As EmployeeTaxInfoWebService.QstDataAllowedDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadAllowedQstCodeResult As EmployeeTaxInfoWebService.QstDataAllowedDTO)
            MyBase.New
            Me.LoadAllowedQstCodeResult = LoadAllowedQstCodeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIsAllowedQstCodeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIsAllowedQstCode", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetIsAllowedQstCodeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public year As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public einkommen As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public childern As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public qstGroup As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public kirchsteuer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public geschlecht As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String)
            MyBase.New
            Me.canton = canton
            Me.year = year
            Me.einkommen = einkommen
            Me.childern = childern
            Me.qstGroup = qstGroup
            Me.kirchsteuer = kirchsteuer
            Me.geschlecht = geschlecht
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIsAllowedQstCodeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIsAllowedQstCodeResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.GetIsAllowedQstCodeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.GetIsAllowedQstCodeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class GetIsAllowedQstCodeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetIsAllowedQstCodeResult As EmployeeTaxInfoWebService.QstDataAllowedDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIsAllowedQstCodeResult As EmployeeTaxInfoWebService.QstDataAllowedDTO)
            MyBase.New
            Me.GetIsAllowedQstCodeResult = GetIsAllowedQstCodeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadChildEducationDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadChildEducationData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadChildEducationDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadChildEducationDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadChildEducationDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public canton As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public year As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal canton As String, ByVal year As Integer)
            MyBase.New
            Me.customerID = customerID
            Me.canton = canton
            Me.year = year
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadChildEducationDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadChildEducationDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/", Order:=0)>  _
        Public Body As EmployeeTaxInfoWebService.LoadChildEducationDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As EmployeeTaxInfoWebService.LoadChildEducationDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPEmployeeTaxInfoService.asmx/")>  _
    Partial Public Class LoadChildEducationDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadChildEducationDataResult As EmployeeTaxInfoWebService.ChildEducationDataDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadChildEducationDataResult As EmployeeTaxInfoWebService.ChildEducationDataDTO)
            MyBase.New
            Me.LoadChildEducationDataResult = LoadChildEducationDataResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SPEmployeeTaxInfoServiceSoapChannel
        Inherits EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SPEmployeeTaxInfoServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap)
        Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_GetTaxInfo(ByVal request As EmployeeTaxInfoWebService.GetTaxInfoRequest) As EmployeeTaxInfoWebService.GetTaxInfoResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.GetTaxInfo
            Return MyBase.Channel.GetTaxInfo(request)
        End Function
        
        Public Function GetTaxInfo(ByVal canton As String, ByVal year As Integer) As EmployeeTaxInfoWebService.TaxDataDTO
            Dim inValue As EmployeeTaxInfoWebService.GetTaxInfoRequest = New EmployeeTaxInfoWebService.GetTaxInfoRequest()
            inValue.Body = New EmployeeTaxInfoWebService.GetTaxInfoRequestBody()
            inValue.Body.canton = canton
            inValue.Body.year = year
            Dim retVal As EmployeeTaxInfoWebService.GetTaxInfoResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).GetTaxInfo(inValue)
            Return retVal.Body.GetTaxInfoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_LoadTaxInfoData(ByVal request As EmployeeTaxInfoWebService.LoadTaxInfoDataRequest) As EmployeeTaxInfoWebService.LoadTaxInfoDataResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.LoadTaxInfoData
            Return MyBase.Channel.LoadTaxInfoData(request)
        End Function
        
        Public Function LoadTaxInfoData(ByVal customerID As String, ByVal canton As String, ByVal year As Integer) As EmployeeTaxInfoWebService.TaxDataDTO
            Dim inValue As EmployeeTaxInfoWebService.LoadTaxInfoDataRequest = New EmployeeTaxInfoWebService.LoadTaxInfoDataRequest()
            inValue.Body = New EmployeeTaxInfoWebService.LoadTaxInfoDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.canton = canton
            inValue.Body.year = year
            Dim retVal As EmployeeTaxInfoWebService.LoadTaxInfoDataResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).LoadTaxInfoData(inValue)
            Return retVal.Body.LoadTaxInfoDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_GetQstData(ByVal request As EmployeeTaxInfoWebService.GetQstDataRequest) As EmployeeTaxInfoWebService.GetQstDataResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.GetQstData
            Return MyBase.Channel.GetQstData(request)
        End Function
        
        Public Function GetQstData(ByVal customerID As String, ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String) As EmployeeTaxInfoWebService.QstDataDTO()
            Dim inValue As EmployeeTaxInfoWebService.GetQstDataRequest = New EmployeeTaxInfoWebService.GetQstDataRequest()
            inValue.Body = New EmployeeTaxInfoWebService.GetQstDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.canton = canton
            inValue.Body.year = year
            inValue.Body.einkommen = einkommen
            inValue.Body.childern = childern
            inValue.Body.qstGroup = qstGroup
            inValue.Body.kirchsteuer = kirchsteuer
            inValue.Body.geschlecht = geschlecht
            Dim retVal As EmployeeTaxInfoWebService.GetQstDataResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).GetQstData(inValue)
            Return retVal.Body.GetQstDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_LoadAllowedQstCode(ByVal request As EmployeeTaxInfoWebService.LoadAllowedQstCodeRequest) As EmployeeTaxInfoWebService.LoadAllowedQstCodeResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.LoadAllowedQstCode
            Return MyBase.Channel.LoadAllowedQstCode(request)
        End Function
        
        Public Function LoadAllowedQstCode(ByVal customerID As String, ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String) As EmployeeTaxInfoWebService.QstDataAllowedDTO
            Dim inValue As EmployeeTaxInfoWebService.LoadAllowedQstCodeRequest = New EmployeeTaxInfoWebService.LoadAllowedQstCodeRequest()
            inValue.Body = New EmployeeTaxInfoWebService.LoadAllowedQstCodeRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.canton = canton
            inValue.Body.year = year
            inValue.Body.einkommen = einkommen
            inValue.Body.childern = childern
            inValue.Body.qstGroup = qstGroup
            inValue.Body.kirchsteuer = kirchsteuer
            inValue.Body.geschlecht = geschlecht
            Dim retVal As EmployeeTaxInfoWebService.LoadAllowedQstCodeResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).LoadAllowedQstCode(inValue)
            Return retVal.Body.LoadAllowedQstCodeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_GetIsAllowedQstCode(ByVal request As EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequest) As EmployeeTaxInfoWebService.GetIsAllowedQstCodeResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.GetIsAllowedQstCode
            Return MyBase.Channel.GetIsAllowedQstCode(request)
        End Function
        
        Public Function GetIsAllowedQstCode(ByVal canton As String, ByVal year As Integer, ByVal einkommen As Double, ByVal childern As Integer, ByVal qstGroup As String, ByVal kirchsteuer As String, ByVal geschlecht As String) As EmployeeTaxInfoWebService.QstDataAllowedDTO
            Dim inValue As EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequest = New EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequest()
            inValue.Body = New EmployeeTaxInfoWebService.GetIsAllowedQstCodeRequestBody()
            inValue.Body.canton = canton
            inValue.Body.year = year
            inValue.Body.einkommen = einkommen
            inValue.Body.childern = childern
            inValue.Body.qstGroup = qstGroup
            inValue.Body.kirchsteuer = kirchsteuer
            inValue.Body.geschlecht = geschlecht
            Dim retVal As EmployeeTaxInfoWebService.GetIsAllowedQstCodeResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).GetIsAllowedQstCode(inValue)
            Return retVal.Body.GetIsAllowedQstCodeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EmployeeTaxInfoWebService_SPEmployeeTaxInfoServiceSoap_LoadChildEducationData(ByVal request As EmployeeTaxInfoWebService.LoadChildEducationDataRequest) As EmployeeTaxInfoWebService.LoadChildEducationDataResponse Implements EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap.LoadChildEducationData
            Return MyBase.Channel.LoadChildEducationData(request)
        End Function
        
        Public Function LoadChildEducationData(ByVal customerID As String, ByVal canton As String, ByVal year As Integer) As EmployeeTaxInfoWebService.ChildEducationDataDTO
            Dim inValue As EmployeeTaxInfoWebService.LoadChildEducationDataRequest = New EmployeeTaxInfoWebService.LoadChildEducationDataRequest()
            inValue.Body = New EmployeeTaxInfoWebService.LoadChildEducationDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.canton = canton
            inValue.Body.year = year
            Dim retVal As EmployeeTaxInfoWebService.LoadChildEducationDataResponse = CType(Me,EmployeeTaxInfoWebService.SPEmployeeTaxInfoServiceSoap).LoadChildEducationData(inValue)
            Return retVal.Body.LoadChildEducationDataResult
        End Function
    End Class
End Namespace
