'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SPBankUtilWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BankSearchResultDTO", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BankSearchResultDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClearingNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BanNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BankNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostcodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SwiftField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelephoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelefaxField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostAccountField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ClearingNumber() As String
            Get
                Return Me.ClearingNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClearingNumberField, value) <> true) Then
                    Me.ClearingNumberField = value
                    Me.RaisePropertyChanged("ClearingNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property BanName() As String
            Get
                Return Me.BanNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BanNameField, value) <> true) Then
                    Me.BanNameField = value
                    Me.RaisePropertyChanged("BanName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property BankName() As String
            Get
                Return Me.BankNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BankNameField, value) <> true) Then
                    Me.BankNameField = value
                    Me.RaisePropertyChanged("BankName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Postcode() As String
            Get
                Return Me.PostcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostcodeField, value) <> true) Then
                    Me.PostcodeField = value
                    Me.RaisePropertyChanged("Postcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Swift() As String
            Get
                Return Me.SwiftField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SwiftField, value) <> true) Then
                    Me.SwiftField = value
                    Me.RaisePropertyChanged("Swift")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Telephone() As String
            Get
                Return Me.TelephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelephoneField, value) <> true) Then
                    Me.TelephoneField = value
                    Me.RaisePropertyChanged("Telephone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Telefax() As String
            Get
                Return Me.TelefaxField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelefaxField, value) <> true) Then
                    Me.TelefaxField = value
                    Me.RaisePropertyChanged("Telefax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property PostAccount() As String
            Get
                Return Me.PostAccountField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostAccountField, value) <> true) Then
                    Me.PostAccountField = value
                    Me.RaisePropertyChanged("PostAccount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IBANConvertResult", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class IBANConvertResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IBANField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PCField As String
        
        Private ResultCodeField As Integer
        
        Private SuccessField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IBAN() As String
            Get
                Return Me.IBANField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IBANField, value) <> true) Then
                    Me.IBANField = value
                    Me.RaisePropertyChanged("IBAN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PC() As String
            Get
                Return Me.PCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PCField, value) <> true) Then
                    Me.PCField = value
                    Me.RaisePropertyChanged("PC")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ResultCode() As Integer
            Get
                Return Me.ResultCodeField
            End Get
            Set
                If (Me.ResultCodeField.Equals(value) <> true) Then
                    Me.ResultCodeField = value
                    Me.RaisePropertyChanged("ResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IBANVersionResult", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class IBANVersionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private MajorVersionField As Integer
        
        Private MinorVersionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidUntilField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property MajorVersion() As Integer
            Get
                Return Me.MajorVersionField
            End Get
            Set
                If (Me.MajorVersionField.Equals(value) <> true) Then
                    Me.MajorVersionField = value
                    Me.RaisePropertyChanged("MajorVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property MinorVersion() As Integer
            Get
                Return Me.MinorVersionField
            End Get
            Set
                If (Me.MinorVersionField.Equals(value) <> true) Then
                    Me.MinorVersionField = value
                    Me.RaisePropertyChanged("MinorVersion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValidUntil() As String
            Get
                Return Me.ValidUntilField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValidUntilField, value) <> true) Then
                    Me.ValidUntilField = value
                    Me.RaisePropertyChanged("ValidUntil")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IBANDecodeResult", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class IBANDecodeResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LandcodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BankIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KontonummerField As String
        
        Private ResultCodeField As SPBankUtilWebService.IBANDecodeResultCode
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Landcode() As String
            Get
                Return Me.LandcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LandcodeField, value) <> true) Then
                    Me.LandcodeField = value
                    Me.RaisePropertyChanged("Landcode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property BankID() As String
            Get
                Return Me.BankIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BankIDField, value) <> true) Then
                    Me.BankIDField = value
                    Me.RaisePropertyChanged("BankID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Kontonummer() As String
            Get
                Return Me.KontonummerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KontonummerField, value) <> true) Then
                    Me.KontonummerField = value
                    Me.RaisePropertyChanged("Kontonummer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property ResultCode() As SPBankUtilWebService.IBANDecodeResultCode
            Get
                Return Me.ResultCodeField
            End Get
            Set
                If (Me.ResultCodeField.Equals(value) <> true) Then
                    Me.ResultCodeField = value
                    Me.RaisePropertyChanged("ResultCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="IBANDecodeResultCode", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Public Enum IBANDecodeResultCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InvalidIBAN = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UnkownIBANCountryCode = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Failure = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", ConfigurationName:="SPBankUtilWebService.SPBankUtilSoap")>  _
    Public Interface SPBankUtilSoap
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname HelloWorldResult aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As SPBankUtilWebService.HelloWorldRequest) As SPBankUtilWebService.HelloWorldResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/LoadBankData", ReplyAction:="*")>  _
        Function LoadBankData(ByVal request As SPBankUtilWebService.LoadBankDataRequest) As SPBankUtilWebService.LoadBankDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/LoadAssignedBankData", ReplyAction:="*")>  _
        Function LoadAssignedBankData(ByVal request As SPBankUtilWebService.LoadAssignedBankDataRequest) As SPBankUtilWebService.LoadAssignedBankDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/EncodeSwissIBAN", ReplyAction:="*")>  _
        Function EncodeSwissIBAN(ByVal request As SPBankUtilWebService.EncodeSwissIBANRequest) As SPBankUtilWebService.EncodeSwissIBANResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/IBANEncodeDLLVersionInf"& _ 
            "o", ReplyAction:="*")>  _
        Function IBANEncodeDLLVersionInfo(ByVal request As SPBankUtilWebService.IBANEncodeDLLVersionInfoRequest) As SPBankUtilWebService.IBANEncodeDLLVersionInfoResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/DecodeIBAN", ReplyAction:="*")>  _
        Function DecodeIBAN(ByVal request As SPBankUtilWebService.DecodeIBANRequest) As SPBankUtilWebService.DecodeIBANResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname clearingNumber aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/GetBankData", ReplyAction:="*")>  _
        Function GetBankData(ByVal request As SPBankUtilWebService.GetBankDataRequest) As SPBankUtilWebService.GetBankDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname clearingNumber aus Namespace http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/GetBankDataByClearingNu"& _ 
            "mber", ReplyAction:="*")>  _
        Function GetBankDataByClearingNumber(ByVal request As SPBankUtilWebService.GetBankDataByClearingNumberRequest) As SPBankUtilWebService.GetBankDataByClearingNumberResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadBankDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadBankData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.LoadBankDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.LoadBankDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class LoadBankDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public clearingNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public bankName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public bankPostcode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public bankLocation As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public swift As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal clearingNumber As String, ByVal bankName As String, ByVal bankPostcode As String, ByVal bankLocation As String, ByVal swift As String)
            MyBase.New
            Me.customerID = customerID
            Me.clearingNumber = clearingNumber
            Me.bankName = bankName
            Me.bankPostcode = bankPostcode
            Me.bankLocation = bankLocation
            Me.swift = swift
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadBankDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadBankDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.LoadBankDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.LoadBankDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class LoadBankDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadBankDataResult() As SPBankUtilWebService.BankSearchResultDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadBankDataResult() As SPBankUtilWebService.BankSearchResultDTO)
            MyBase.New
            Me.LoadBankDataResult = LoadBankDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAssignedBankDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAssignedBankData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.LoadAssignedBankDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.LoadAssignedBankDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class LoadAssignedBankDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public clearingNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public bankName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public bankLocation As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal clearingNumber As String, ByVal bankName As String, ByVal bankLocation As String)
            MyBase.New
            Me.customerID = customerID
            Me.clearingNumber = clearingNumber
            Me.bankName = bankName
            Me.bankLocation = bankLocation
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadAssignedBankDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadAssignedBankDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.LoadAssignedBankDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.LoadAssignedBankDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class LoadAssignedBankDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadAssignedBankDataResult As SPBankUtilWebService.BankSearchResultDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadAssignedBankDataResult As SPBankUtilWebService.BankSearchResultDTO)
            MyBase.New
            Me.LoadAssignedBankDataResult = LoadAssignedBankDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncodeSwissIBANRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncodeSwissIBAN", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.EncodeSwissIBANRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.EncodeSwissIBANRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class EncodeSwissIBANRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public bcPC_Or_SwiftBicNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public accountNumber As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal bcPC_Or_SwiftBicNumber As String, ByVal accountNumber As String)
            MyBase.New
            Me.customerID = customerID
            Me.bcPC_Or_SwiftBicNumber = bcPC_Or_SwiftBicNumber
            Me.accountNumber = accountNumber
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncodeSwissIBANResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncodeSwissIBANResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.EncodeSwissIBANResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.EncodeSwissIBANResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class EncodeSwissIBANResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EncodeSwissIBANResult As SPBankUtilWebService.IBANConvertResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncodeSwissIBANResult As SPBankUtilWebService.IBANConvertResult)
            MyBase.New
            Me.EncodeSwissIBANResult = EncodeSwissIBANResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IBANEncodeDLLVersionInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IBANEncodeDLLVersionInfo", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.IBANEncodeDLLVersionInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.IBANEncodeDLLVersionInfoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class IBANEncodeDLLVersionInfoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String)
            MyBase.New
            Me.customerID = customerID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IBANEncodeDLLVersionInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IBANEncodeDLLVersionInfoResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.IBANEncodeDLLVersionInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.IBANEncodeDLLVersionInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class IBANEncodeDLLVersionInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IBANEncodeDLLVersionInfoResult As SPBankUtilWebService.IBANVersionResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IBANEncodeDLLVersionInfoResult As SPBankUtilWebService.IBANVersionResult)
            MyBase.New
            Me.IBANEncodeDLLVersionInfoResult = IBANEncodeDLLVersionInfoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DecodeIBANRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DecodeIBAN", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.DecodeIBANRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.DecodeIBANRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class DecodeIBANRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public iban As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal iban As String)
            MyBase.New
            Me.customerID = customerID
            Me.iban = iban
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DecodeIBANResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DecodeIBANResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.DecodeIBANResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.DecodeIBANResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class DecodeIBANResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DecodeIBANResult As SPBankUtilWebService.IBANDecodeResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DecodeIBANResult As SPBankUtilWebService.IBANDecodeResult)
            MyBase.New
            Me.DecodeIBANResult = DecodeIBANResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBankDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBankData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.GetBankDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.GetBankDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class GetBankDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public clearingNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public bankName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public bankPostcode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public bankLocation As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public swift As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal clearingNumber As String, ByVal bankName As String, ByVal bankPostcode As String, ByVal bankLocation As String, ByVal swift As String)
            MyBase.New
            Me.clearingNumber = clearingNumber
            Me.bankName = bankName
            Me.bankPostcode = bankPostcode
            Me.bankLocation = bankLocation
            Me.swift = swift
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBankDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBankDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.GetBankDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.GetBankDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class GetBankDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetBankDataResult() As SPBankUtilWebService.BankSearchResultDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetBankDataResult() As SPBankUtilWebService.BankSearchResultDTO)
            MyBase.New
            Me.GetBankDataResult = GetBankDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBankDataByClearingNumberRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBankDataByClearingNumber", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.GetBankDataByClearingNumberRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.GetBankDataByClearingNumberRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class GetBankDataByClearingNumberRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public clearingNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public location As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal clearingNumber As String, ByVal location As String)
            MyBase.New
            Me.clearingNumber = clearingNumber
            Me.location = location
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetBankDataByClearingNumberResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetBankDataByClearingNumberResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/", Order:=0)>  _
        Public Body As SPBankUtilWebService.GetBankDataByClearingNumberResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPBankUtilWebService.GetBankDataByClearingNumberResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPBankUtil.asmx/")>  _
    Partial Public Class GetBankDataByClearingNumberResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetBankDataByClearingNumberResult As SPBankUtilWebService.BankSearchResultDTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetBankDataByClearingNumberResult As SPBankUtilWebService.BankSearchResultDTO)
            MyBase.New
            Me.GetBankDataByClearingNumberResult = GetBankDataByClearingNumberResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SPBankUtilSoapChannel
        Inherits SPBankUtilWebService.SPBankUtilSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SPBankUtilSoapClient
        Inherits System.ServiceModel.ClientBase(Of SPBankUtilWebService.SPBankUtilSoap)
        Implements SPBankUtilWebService.SPBankUtilSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_HelloWorld(ByVal request As SPBankUtilWebService.HelloWorldRequest) As SPBankUtilWebService.HelloWorldResponse Implements SPBankUtilWebService.SPBankUtilSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As SPBankUtilWebService.HelloWorldRequest = New SPBankUtilWebService.HelloWorldRequest()
            inValue.Body = New SPBankUtilWebService.HelloWorldRequestBody()
            Dim retVal As SPBankUtilWebService.HelloWorldResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_LoadBankData(ByVal request As SPBankUtilWebService.LoadBankDataRequest) As SPBankUtilWebService.LoadBankDataResponse Implements SPBankUtilWebService.SPBankUtilSoap.LoadBankData
            Return MyBase.Channel.LoadBankData(request)
        End Function
        
        Public Function LoadBankData(ByVal customerID As String, ByVal clearingNumber As String, ByVal bankName As String, ByVal bankPostcode As String, ByVal bankLocation As String, ByVal swift As String) As SPBankUtilWebService.BankSearchResultDTO()
            Dim inValue As SPBankUtilWebService.LoadBankDataRequest = New SPBankUtilWebService.LoadBankDataRequest()
            inValue.Body = New SPBankUtilWebService.LoadBankDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.clearingNumber = clearingNumber
            inValue.Body.bankName = bankName
            inValue.Body.bankPostcode = bankPostcode
            inValue.Body.bankLocation = bankLocation
            inValue.Body.swift = swift
            Dim retVal As SPBankUtilWebService.LoadBankDataResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).LoadBankData(inValue)
            Return retVal.Body.LoadBankDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_LoadAssignedBankData(ByVal request As SPBankUtilWebService.LoadAssignedBankDataRequest) As SPBankUtilWebService.LoadAssignedBankDataResponse Implements SPBankUtilWebService.SPBankUtilSoap.LoadAssignedBankData
            Return MyBase.Channel.LoadAssignedBankData(request)
        End Function
        
        Public Function LoadAssignedBankData(ByVal customerID As String, ByVal clearingNumber As String, ByVal bankName As String, ByVal bankLocation As String) As SPBankUtilWebService.BankSearchResultDTO
            Dim inValue As SPBankUtilWebService.LoadAssignedBankDataRequest = New SPBankUtilWebService.LoadAssignedBankDataRequest()
            inValue.Body = New SPBankUtilWebService.LoadAssignedBankDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.clearingNumber = clearingNumber
            inValue.Body.bankName = bankName
            inValue.Body.bankLocation = bankLocation
            Dim retVal As SPBankUtilWebService.LoadAssignedBankDataResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).LoadAssignedBankData(inValue)
            Return retVal.Body.LoadAssignedBankDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_EncodeSwissIBAN(ByVal request As SPBankUtilWebService.EncodeSwissIBANRequest) As SPBankUtilWebService.EncodeSwissIBANResponse Implements SPBankUtilWebService.SPBankUtilSoap.EncodeSwissIBAN
            Return MyBase.Channel.EncodeSwissIBAN(request)
        End Function
        
        Public Function EncodeSwissIBAN(ByVal customerID As String, ByVal bcPC_Or_SwiftBicNumber As String, ByVal accountNumber As String) As SPBankUtilWebService.IBANConvertResult
            Dim inValue As SPBankUtilWebService.EncodeSwissIBANRequest = New SPBankUtilWebService.EncodeSwissIBANRequest()
            inValue.Body = New SPBankUtilWebService.EncodeSwissIBANRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.bcPC_Or_SwiftBicNumber = bcPC_Or_SwiftBicNumber
            inValue.Body.accountNumber = accountNumber
            Dim retVal As SPBankUtilWebService.EncodeSwissIBANResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).EncodeSwissIBAN(inValue)
            Return retVal.Body.EncodeSwissIBANResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_IBANEncodeDLLVersionInfo(ByVal request As SPBankUtilWebService.IBANEncodeDLLVersionInfoRequest) As SPBankUtilWebService.IBANEncodeDLLVersionInfoResponse Implements SPBankUtilWebService.SPBankUtilSoap.IBANEncodeDLLVersionInfo
            Return MyBase.Channel.IBANEncodeDLLVersionInfo(request)
        End Function
        
        Public Function IBANEncodeDLLVersionInfo(ByVal customerID As String) As SPBankUtilWebService.IBANVersionResult
            Dim inValue As SPBankUtilWebService.IBANEncodeDLLVersionInfoRequest = New SPBankUtilWebService.IBANEncodeDLLVersionInfoRequest()
            inValue.Body = New SPBankUtilWebService.IBANEncodeDLLVersionInfoRequestBody()
            inValue.Body.customerID = customerID
            Dim retVal As SPBankUtilWebService.IBANEncodeDLLVersionInfoResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).IBANEncodeDLLVersionInfo(inValue)
            Return retVal.Body.IBANEncodeDLLVersionInfoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_DecodeIBAN(ByVal request As SPBankUtilWebService.DecodeIBANRequest) As SPBankUtilWebService.DecodeIBANResponse Implements SPBankUtilWebService.SPBankUtilSoap.DecodeIBAN
            Return MyBase.Channel.DecodeIBAN(request)
        End Function
        
        Public Function DecodeIBAN(ByVal customerID As String, ByVal iban As String) As SPBankUtilWebService.IBANDecodeResult
            Dim inValue As SPBankUtilWebService.DecodeIBANRequest = New SPBankUtilWebService.DecodeIBANRequest()
            inValue.Body = New SPBankUtilWebService.DecodeIBANRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.iban = iban
            Dim retVal As SPBankUtilWebService.DecodeIBANResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).DecodeIBAN(inValue)
            Return retVal.Body.DecodeIBANResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_GetBankData(ByVal request As SPBankUtilWebService.GetBankDataRequest) As SPBankUtilWebService.GetBankDataResponse Implements SPBankUtilWebService.SPBankUtilSoap.GetBankData
            Return MyBase.Channel.GetBankData(request)
        End Function
        
        Public Function GetBankData(ByVal clearingNumber As String, ByVal bankName As String, ByVal bankPostcode As String, ByVal bankLocation As String, ByVal swift As String) As SPBankUtilWebService.BankSearchResultDTO()
            Dim inValue As SPBankUtilWebService.GetBankDataRequest = New SPBankUtilWebService.GetBankDataRequest()
            inValue.Body = New SPBankUtilWebService.GetBankDataRequestBody()
            inValue.Body.clearingNumber = clearingNumber
            inValue.Body.bankName = bankName
            inValue.Body.bankPostcode = bankPostcode
            inValue.Body.bankLocation = bankLocation
            inValue.Body.swift = swift
            Dim retVal As SPBankUtilWebService.GetBankDataResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).GetBankData(inValue)
            Return retVal.Body.GetBankDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPBankUtilWebService_SPBankUtilSoap_GetBankDataByClearingNumber(ByVal request As SPBankUtilWebService.GetBankDataByClearingNumberRequest) As SPBankUtilWebService.GetBankDataByClearingNumberResponse Implements SPBankUtilWebService.SPBankUtilSoap.GetBankDataByClearingNumber
            Return MyBase.Channel.GetBankDataByClearingNumber(request)
        End Function
        
        Public Function GetBankDataByClearingNumber(ByVal clearingNumber As String, ByVal location As String) As SPBankUtilWebService.BankSearchResultDTO
            Dim inValue As SPBankUtilWebService.GetBankDataByClearingNumberRequest = New SPBankUtilWebService.GetBankDataByClearingNumberRequest()
            inValue.Body = New SPBankUtilWebService.GetBankDataByClearingNumberRequestBody()
            inValue.Body.clearingNumber = clearingNumber
            inValue.Body.location = location
            Dim retVal As SPBankUtilWebService.GetBankDataByClearingNumberResponse = CType(Me,SPBankUtilWebService.SPBankUtilSoap).GetBankDataByClearingNumber(inValue)
            Return retVal.Body.GetBankDataByClearingNumberResult
        End Function
    End Class
End Namespace
