'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SPX28ProfilmatcherWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProfilMatcherNotificationData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProfilMatcherNotificationData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QueryNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QueryContentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QueryResultContentField As String
        
        Private TotalField As Integer
        
        Private CustomerNumberField As System.Nullable(Of Integer)
        
        Private EmployeeNumberField As System.Nullable(Of Integer)
        
        Private NotifyField As System.Nullable(Of Boolean)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedFromField As String
        
        Private CreatedOnField As System.Nullable(Of Date)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CustomerID() As String
            Get
                Return Me.CustomerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerIDField, value) <> true) Then
                    Me.CustomerIDField = value
                    Me.RaisePropertyChanged("CustomerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property QueryName() As String
            Get
                Return Me.QueryNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QueryNameField, value) <> true) Then
                    Me.QueryNameField = value
                    Me.RaisePropertyChanged("QueryName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property QueryContent() As String
            Get
                Return Me.QueryContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QueryContentField, value) <> true) Then
                    Me.QueryContentField = value
                    Me.RaisePropertyChanged("QueryContent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property QueryResultContent() As String
            Get
                Return Me.QueryResultContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QueryResultContentField, value) <> true) Then
                    Me.QueryResultContentField = value
                    Me.RaisePropertyChanged("QueryResultContent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property Total() As Integer
            Get
                Return Me.TotalField
            End Get
            Set
                If (Me.TotalField.Equals(value) <> true) Then
                    Me.TotalField = value
                    Me.RaisePropertyChanged("Total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property CustomerNumber() As System.Nullable(Of Integer)
            Get
                Return Me.CustomerNumberField
            End Get
            Set
                If (Me.CustomerNumberField.Equals(value) <> true) Then
                    Me.CustomerNumberField = value
                    Me.RaisePropertyChanged("CustomerNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property EmployeeNumber() As System.Nullable(Of Integer)
            Get
                Return Me.EmployeeNumberField
            End Get
            Set
                If (Me.EmployeeNumberField.Equals(value) <> true) Then
                    Me.EmployeeNumberField = value
                    Me.RaisePropertyChanged("EmployeeNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property Notify() As System.Nullable(Of Boolean)
            Get
                Return Me.NotifyField
            End Get
            Set
                If (Me.NotifyField.Equals(value) <> true) Then
                    Me.NotifyField = value
                    Me.RaisePropertyChanged("Notify")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property CreatedFrom() As String
            Get
                Return Me.CreatedFromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CreatedFromField, value) <> true) Then
                    Me.CreatedFromField = value
                    Me.RaisePropertyChanged("CreatedFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Public Property CreatedOn() As System.Nullable(Of Date)
            Get
                Return Me.CreatedOnField
            End Get
            Set
                If (Me.CreatedOnField.Equals(value) <> true) Then
                    Me.CreatedOnField = value
                    Me.RaisePropertyChanged("CreatedOn")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProfilmatcherQueryData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProfilmatcherQueryData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TermsField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompaniesField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanysizesField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IndustriesField As SPX28ProfilmatcherWebService.ArrayOfString
        
        Private RecruitmentagenciesField As Boolean
        
        Private ManagementField As Boolean
        
        Private TemporaryField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegionsField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationsField() As SPX28ProfilmatcherWebService.ProfilMatcherLocationData
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationDistanceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClustersField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExperiencesField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EducationsField As SPX28ProfilmatcherWebService.ArrayOfString
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SkillsField As SPX28ProfilmatcherWebService.ArrayOfString
        
        Private WorkquotaMinimumField As Integer
        
        Private WorkquotaMaximumField As Integer
        
        Private DateFromField As Date
        
        Private DateToField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SizeField As String
        
        Private CreatedOnField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CustomerID() As String
            Get
                Return Me.CustomerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerIDField, value) <> true) Then
                    Me.CustomerIDField = value
                    Me.RaisePropertyChanged("CustomerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property UserID() As String
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIDField, value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Terms() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.TermsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TermsField, value) <> true) Then
                    Me.TermsField = value
                    Me.RaisePropertyChanged("Terms")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Companies() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.CompaniesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompaniesField, value) <> true) Then
                    Me.CompaniesField = value
                    Me.RaisePropertyChanged("Companies")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Companysizes() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.CompanysizesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanysizesField, value) <> true) Then
                    Me.CompanysizesField = value
                    Me.RaisePropertyChanged("Companysizes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Industries() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.IndustriesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IndustriesField, value) <> true) Then
                    Me.IndustriesField = value
                    Me.RaisePropertyChanged("Industries")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property Recruitmentagencies() As Boolean
            Get
                Return Me.RecruitmentagenciesField
            End Get
            Set
                If (Me.RecruitmentagenciesField.Equals(value) <> true) Then
                    Me.RecruitmentagenciesField = value
                    Me.RaisePropertyChanged("Recruitmentagencies")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property Management() As Boolean
            Get
                Return Me.ManagementField
            End Get
            Set
                If (Me.ManagementField.Equals(value) <> true) Then
                    Me.ManagementField = value
                    Me.RaisePropertyChanged("Management")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property Temporary() As Boolean
            Get
                Return Me.TemporaryField
            End Get
            Set
                If (Me.TemporaryField.Equals(value) <> true) Then
                    Me.TemporaryField = value
                    Me.RaisePropertyChanged("Temporary")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Regions() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.RegionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegionsField, value) <> true) Then
                    Me.RegionsField = value
                    Me.RaisePropertyChanged("Regions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property Locations() As SPX28ProfilmatcherWebService.ProfilMatcherLocationData()
            Get
                Return Me.LocationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationsField, value) <> true) Then
                    Me.LocationsField = value
                    Me.RaisePropertyChanged("Locations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property LocationDistance() As String
            Get
                Return Me.LocationDistanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationDistanceField, value) <> true) Then
                    Me.LocationDistanceField = value
                    Me.RaisePropertyChanged("LocationDistance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property Clusters() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.ClustersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClustersField, value) <> true) Then
                    Me.ClustersField = value
                    Me.RaisePropertyChanged("Clusters")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Experiences() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.ExperiencesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExperiencesField, value) <> true) Then
                    Me.ExperiencesField = value
                    Me.RaisePropertyChanged("Experiences")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property Educations() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.EducationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EducationsField, value) <> true) Then
                    Me.EducationsField = value
                    Me.RaisePropertyChanged("Educations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property Skills() As SPX28ProfilmatcherWebService.ArrayOfString
            Get
                Return Me.SkillsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SkillsField, value) <> true) Then
                    Me.SkillsField = value
                    Me.RaisePropertyChanged("Skills")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=17)>  _
        Public Property WorkquotaMinimum() As Integer
            Get
                Return Me.WorkquotaMinimumField
            End Get
            Set
                If (Me.WorkquotaMinimumField.Equals(value) <> true) Then
                    Me.WorkquotaMinimumField = value
                    Me.RaisePropertyChanged("WorkquotaMinimum")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=18)>  _
        Public Property WorkquotaMaximum() As Integer
            Get
                Return Me.WorkquotaMaximumField
            End Get
            Set
                If (Me.WorkquotaMaximumField.Equals(value) <> true) Then
                    Me.WorkquotaMaximumField = value
                    Me.RaisePropertyChanged("WorkquotaMaximum")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=19)>  _
        Public Property DateFrom() As Date
            Get
                Return Me.DateFromField
            End Get
            Set
                If (Me.DateFromField.Equals(value) <> true) Then
                    Me.DateFromField = value
                    Me.RaisePropertyChanged("DateFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=20)>  _
        Public Property DateTo() As Date
            Get
                Return Me.DateToField
            End Get
            Set
                If (Me.DateToField.Equals(value) <> true) Then
                    Me.DateToField = value
                    Me.RaisePropertyChanged("DateTo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=21)>  _
        Public Property Page() As String
            Get
                Return Me.PageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PageField, value) <> true) Then
                    Me.PageField = value
                    Me.RaisePropertyChanged("Page")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property Size() As String
            Get
                Return Me.SizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SizeField, value) <> true) Then
                    Me.SizeField = value
                    Me.RaisePropertyChanged("Size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=23)>  _
        Public Property CreatedOn() As Date
            Get
                Return Me.CreatedOnField
            End Get
            Set
                If (Me.CreatedOnField.Equals(value) <> true) Then
                    Me.CreatedOnField = value
                    Me.RaisePropertyChanged("CreatedOn")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProfilMatcherLocationData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProfilMatcherLocationData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        Private LocationDistancesField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property LocationDistances() As Integer
            Get
                Return Me.LocationDistancesField
            End Get
            Set
                If (Me.LocationDistancesField.Equals(value) <> true) Then
                    Me.LocationDistancesField = value
                    Me.RaisePropertyChanged("LocationDistances")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProfilmatcherQueryResultData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProfilmatcherQueryResultData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomerIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        Private TotalField As Integer
        
        Private PageField As Integer
        
        Private SizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultContentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private JobsField() As SPX28ProfilmatcherWebService.ProfilmatcherQueryJob
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CustomerID() As String
            Get
                Return Me.CustomerIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomerIDField, value) <> true) Then
                    Me.CustomerIDField = value
                    Me.RaisePropertyChanged("CustomerID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Total() As Integer
            Get
                Return Me.TotalField
            End Get
            Set
                If (Me.TotalField.Equals(value) <> true) Then
                    Me.TotalField = value
                    Me.RaisePropertyChanged("Total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Page() As Integer
            Get
                Return Me.PageField
            End Get
            Set
                If (Me.PageField.Equals(value) <> true) Then
                    Me.PageField = value
                    Me.RaisePropertyChanged("Page")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Size() As Integer
            Get
                Return Me.SizeField
            End Get
            Set
                If (Me.SizeField.Equals(value) <> true) Then
                    Me.SizeField = value
                    Me.RaisePropertyChanged("Size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property ResultContent() As String
            Get
                Return Me.ResultContentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultContentField, value) <> true) Then
                    Me.ResultContentField = value
                    Me.RaisePropertyChanged("ResultContent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Jobs() As SPX28ProfilmatcherWebService.ProfilmatcherQueryJob()
            Get
                Return Me.JobsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.JobsField, value) <> true) Then
                    Me.JobsField = value
                    Me.RaisePropertyChanged("Jobs")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProfilmatcherQueryJob", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ProfilmatcherQueryJob
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IDField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private URLField As String
        
        Private DateCreatedField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ID() As Long
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property URL() As String
            Get
                Return Me.URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.URLField, value) <> true) Then
                    Me.URLField = value
                    Me.RaisePropertyChanged("URL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property DateCreated() As Date
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Me.DateCreatedField.Equals(value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", ConfigurationName:="SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap")>  _
    Public Interface SPX28ProfilmatcherSoap
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname HelloWorldResult aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As SPX28ProfilmatcherWebService.HelloWorldRequest) As SPX28ProfilmatcherWebService.HelloWorldResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/LoadPMQueryNoti"& _ 
            "fications", ReplyAction:="*")>  _
        Function LoadPMQueryNotifications(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequest) As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/LoadPMQueryAssi"& _ 
            "gnedNotifications", ReplyAction:="*")>  _
        Function LoadPMQueryAssignedNotifications(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequest) As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/SavePMQueryNoti"& _ 
            "ficationData", ReplyAction:="*")>  _
        Function SavePMQueryNotificationData(ByVal request As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequest) As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/DeletePMQueryAs"& _ 
            "signedNotificationData", ReplyAction:="*")>  _
        Function DeletePMQueryAssignedNotificationData(ByVal request As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequest) As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/BuildPMQueryStr"& _ 
            "ing", ReplyAction:="*")>  _
        Function BuildPMQueryString(ByVal request As SPX28ProfilmatcherWebService.BuildPMQueryStringRequest) As SPX28ProfilmatcherWebService.BuildPMQueryStringResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/LoadPMQueryResu"& _ 
            "ltData", ReplyAction:="*")>  _
        Function LoadPMQueryResultData(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequest) As SPX28ProfilmatcherWebService.LoadPMQueryResultDataResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname customerID aus Namespace http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/LoadPMQueryResu"& _ 
            "ltDa", ReplyAction:="*")>  _
        Function LoadPMQueryResultDa(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequest) As SPX28ProfilmatcherWebService.LoadPMQueryResultDaResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryNotificationsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryNotifications", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryNotificationsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public customerNumber As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public employeeNumber As System.Nullable(Of Integer)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal userID As String, ByVal customerNumber As System.Nullable(Of Integer), ByVal employeeNumber As System.Nullable(Of Integer))
            MyBase.New
            Me.customerID = customerID
            Me.userID = userID
            Me.customerNumber = customerNumber
            Me.employeeNumber = employeeNumber
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryNotificationsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryNotificationsResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryNotificationsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadPMQueryNotificationsResult() As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadPMQueryNotificationsResult() As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData)
            MyBase.New
            Me.LoadPMQueryNotificationsResult = LoadPMQueryNotificationsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryAssignedNotificationsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryAssignedNotifications", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryAssignedNotificationsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal id As Integer)
            MyBase.New
            Me.customerID = customerID
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryAssignedNotificationsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryAssignedNotificationsResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryAssignedNotificationsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadPMQueryAssignedNotificationsResult As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadPMQueryAssignedNotificationsResult As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData)
            MyBase.New
            Me.LoadPMQueryAssignedNotificationsResult = LoadPMQueryAssignedNotificationsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SavePMQueryNotificationDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SavePMQueryNotificationData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class SavePMQueryNotificationDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public customerNumber As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public employeeNumber As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public notify As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public createdFrom As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public tplName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public pmQueryString As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public pmQueryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public pmJobResult As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal userID As String, ByVal customerNumber As System.Nullable(Of Integer), ByVal employeeNumber As System.Nullable(Of Integer), ByVal notify As Boolean, ByVal createdFrom As String, ByVal tplName As String, ByVal pmQueryString As String, ByVal pmQueryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData, ByVal pmJobResult As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData)
            MyBase.New
            Me.customerID = customerID
            Me.userID = userID
            Me.customerNumber = customerNumber
            Me.employeeNumber = employeeNumber
            Me.notify = notify
            Me.createdFrom = createdFrom
            Me.tplName = tplName
            Me.pmQueryString = pmQueryString
            Me.pmQueryData = pmQueryData
            Me.pmJobResult = pmJobResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SavePMQueryNotificationDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SavePMQueryNotificationDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class SavePMQueryNotificationDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SavePMQueryNotificationDataResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SavePMQueryNotificationDataResult As Boolean)
            MyBase.New
            Me.SavePMQueryNotificationDataResult = SavePMQueryNotificationDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletePMQueryAssignedNotificationDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeletePMQueryAssignedNotificationData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class DeletePMQueryAssignedNotificationDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public ID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal ID As Integer)
            MyBase.New
            Me.customerID = customerID
            Me.ID = ID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletePMQueryAssignedNotificationDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeletePMQueryAssignedNotificationDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class DeletePMQueryAssignedNotificationDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public DeletePMQueryAssignedNotificationDataResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DeletePMQueryAssignedNotificationDataResult As Boolean)
            MyBase.New
            Me.DeletePMQueryAssignedNotificationDataResult = DeletePMQueryAssignedNotificationDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuildPMQueryStringRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuildPMQueryString", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.BuildPMQueryStringRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.BuildPMQueryStringRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class BuildPMQueryStringRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData)
            MyBase.New
            Me.customerID = customerID
            Me.userID = userID
            Me.queryData = queryData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuildPMQueryStringResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuildPMQueryStringResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.BuildPMQueryStringResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.BuildPMQueryStringResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class BuildPMQueryStringResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public BuildPMQueryStringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal BuildPMQueryStringResult As String)
            MyBase.New
            Me.BuildPMQueryStringResult = BuildPMQueryStringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryResultDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryResultData", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryResultDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData)
            MyBase.New
            Me.customerID = customerID
            Me.userID = userID
            Me.queryData = queryData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryResultDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryResultDataResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryResultDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadPMQueryResultDataResult As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadPMQueryResultDataResult As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData)
            MyBase.New
            Me.LoadPMQueryResultDataResult = LoadPMQueryResultDataResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryResultDaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryResultDa", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryResultDaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public customerID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public userID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData)
            MyBase.New
            Me.customerID = customerID
            Me.userID = userID
            Me.queryData = queryData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoadPMQueryResultDaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoadPMQueryResultDaResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/", Order:=0)>  _
        Public Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SPX28ProfilmatcherWebService.LoadPMQueryResultDaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPX28Profilmatcher.asmx/")>  _
    Partial Public Class LoadPMQueryResultDaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LoadPMQueryResultDaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoadPMQueryResultDaResult As String)
            MyBase.New
            Me.LoadPMQueryResultDaResult = LoadPMQueryResultDaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SPX28ProfilmatcherSoapChannel
        Inherits SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SPX28ProfilmatcherSoapClient
        Inherits System.ServiceModel.ClientBase(Of SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap)
        Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_HelloWorld(ByVal request As SPX28ProfilmatcherWebService.HelloWorldRequest) As SPX28ProfilmatcherWebService.HelloWorldResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As SPX28ProfilmatcherWebService.HelloWorldRequest = New SPX28ProfilmatcherWebService.HelloWorldRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.HelloWorldRequestBody()
            Dim retVal As SPX28ProfilmatcherWebService.HelloWorldResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_LoadPMQueryNotifications(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequest) As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.LoadPMQueryNotifications
            Return MyBase.Channel.LoadPMQueryNotifications(request)
        End Function
        
        Public Function LoadPMQueryNotifications(ByVal customerID As String, ByVal userID As String, ByVal customerNumber As System.Nullable(Of Integer), ByVal employeeNumber As System.Nullable(Of Integer)) As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData()
            Dim inValue As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequest = New SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.LoadPMQueryNotificationsRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.userID = userID
            inValue.Body.customerNumber = customerNumber
            inValue.Body.employeeNumber = employeeNumber
            Dim retVal As SPX28ProfilmatcherWebService.LoadPMQueryNotificationsResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).LoadPMQueryNotifications(inValue)
            Return retVal.Body.LoadPMQueryNotificationsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_LoadPMQueryAssignedNotifications(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequest) As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.LoadPMQueryAssignedNotifications
            Return MyBase.Channel.LoadPMQueryAssignedNotifications(request)
        End Function
        
        Public Function LoadPMQueryAssignedNotifications(ByVal customerID As String, ByVal id As Integer) As SPX28ProfilmatcherWebService.ProfilMatcherNotificationData
            Dim inValue As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequest = New SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.id = id
            Dim retVal As SPX28ProfilmatcherWebService.LoadPMQueryAssignedNotificationsResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).LoadPMQueryAssignedNotifications(inValue)
            Return retVal.Body.LoadPMQueryAssignedNotificationsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_SavePMQueryNotificationData(ByVal request As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequest) As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.SavePMQueryNotificationData
            Return MyBase.Channel.SavePMQueryNotificationData(request)
        End Function
        
        Public Function SavePMQueryNotificationData(ByVal customerID As String, ByVal userID As String, ByVal customerNumber As System.Nullable(Of Integer), ByVal employeeNumber As System.Nullable(Of Integer), ByVal notify As Boolean, ByVal createdFrom As String, ByVal tplName As String, ByVal pmQueryString As String, ByVal pmQueryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData, ByVal pmJobResult As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData) As Boolean
            Dim inValue As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequest = New SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.SavePMQueryNotificationDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.userID = userID
            inValue.Body.customerNumber = customerNumber
            inValue.Body.employeeNumber = employeeNumber
            inValue.Body.notify = notify
            inValue.Body.createdFrom = createdFrom
            inValue.Body.tplName = tplName
            inValue.Body.pmQueryString = pmQueryString
            inValue.Body.pmQueryData = pmQueryData
            inValue.Body.pmJobResult = pmJobResult
            Dim retVal As SPX28ProfilmatcherWebService.SavePMQueryNotificationDataResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).SavePMQueryNotificationData(inValue)
            Return retVal.Body.SavePMQueryNotificationDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_DeletePMQueryAssignedNotificationData(ByVal request As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequest) As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.DeletePMQueryAssignedNotificationData
            Return MyBase.Channel.DeletePMQueryAssignedNotificationData(request)
        End Function
        
        Public Function DeletePMQueryAssignedNotificationData(ByVal customerID As String, ByVal ID As Integer) As Boolean
            Dim inValue As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequest = New SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.ID = ID
            Dim retVal As SPX28ProfilmatcherWebService.DeletePMQueryAssignedNotificationDataResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).DeletePMQueryAssignedNotificationData(inValue)
            Return retVal.Body.DeletePMQueryAssignedNotificationDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_BuildPMQueryString(ByVal request As SPX28ProfilmatcherWebService.BuildPMQueryStringRequest) As SPX28ProfilmatcherWebService.BuildPMQueryStringResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.BuildPMQueryString
            Return MyBase.Channel.BuildPMQueryString(request)
        End Function
        
        Public Function BuildPMQueryString(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData) As String
            Dim inValue As SPX28ProfilmatcherWebService.BuildPMQueryStringRequest = New SPX28ProfilmatcherWebService.BuildPMQueryStringRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.BuildPMQueryStringRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.userID = userID
            inValue.Body.queryData = queryData
            Dim retVal As SPX28ProfilmatcherWebService.BuildPMQueryStringResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).BuildPMQueryString(inValue)
            Return retVal.Body.BuildPMQueryStringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_LoadPMQueryResultData(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequest) As SPX28ProfilmatcherWebService.LoadPMQueryResultDataResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.LoadPMQueryResultData
            Return MyBase.Channel.LoadPMQueryResultData(request)
        End Function
        
        Public Function LoadPMQueryResultData(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData) As SPX28ProfilmatcherWebService.ProfilmatcherQueryResultData
            Dim inValue As SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequest = New SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.LoadPMQueryResultDataRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.userID = userID
            inValue.Body.queryData = queryData
            Dim retVal As SPX28ProfilmatcherWebService.LoadPMQueryResultDataResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).LoadPMQueryResultData(inValue)
            Return retVal.Body.LoadPMQueryResultDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SPX28ProfilmatcherWebService_SPX28ProfilmatcherSoap_LoadPMQueryResultDa(ByVal request As SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequest) As SPX28ProfilmatcherWebService.LoadPMQueryResultDaResponse Implements SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap.LoadPMQueryResultDa
            Return MyBase.Channel.LoadPMQueryResultDa(request)
        End Function
        
        Public Function LoadPMQueryResultDa(ByVal customerID As String, ByVal userID As String, ByVal queryData As SPX28ProfilmatcherWebService.ProfilmatcherQueryData) As String
            Dim inValue As SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequest = New SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequest()
            inValue.Body = New SPX28ProfilmatcherWebService.LoadPMQueryResultDaRequestBody()
            inValue.Body.customerID = customerID
            inValue.Body.userID = userID
            inValue.Body.queryData = queryData
            Dim retVal As SPX28ProfilmatcherWebService.LoadPMQueryResultDaResponse = CType(Me,SPX28ProfilmatcherWebService.SPX28ProfilmatcherSoap).LoadPMQueryResultDa(inValue)
            Return retVal.Body.LoadPMQueryResultDaResult
        End Function
    End Class
End Namespace
