'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmWidth() As Integer
            Get
                Return CType(Me("ifrmWidth"),Integer)
            End Get
            Set
                Me("ifrmWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmHeight() As Integer
            Get
                Return CType(Me("ifrmHeight"),Integer)
            End Get
            Set
                Me("ifrmHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frm_Location() As String
            Get
                Return CType(Me("frm_Location"),String)
            End Get
            Set
                Me("frm_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LV_1_Size() As String
            Get
                Return CType(Me("LV_1_Size"),String)
            End Get
            Set
                Me("LV_1_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmWidth_2() As Integer
            Get
                Return CType(Me("ifrmWidth_2"),Integer)
            End Get
            Set
                Me("ifrmWidth_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmHeight_2() As Integer
            Get
                Return CType(Me("ifrmHeight_2"),Integer)
            End Get
            Set
                Me("ifrmHeight_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frm_Location_2() As String
            Get
                Return CType(Me("frm_Location_2"),String)
            End Get
            Set
                Me("frm_Location_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LV_2_Size() As String
            Get
                Return CType(Me("LV_2_Size"),String)
            End Get
            Set
                Me("LV_2_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LV_3_Size() As String
            Get
                Return CType(Me("LV_3_Size"),String)
            End Get
            Set
                Me("LV_3_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExportFields() As String
            Get
                Return CType(Me("ExportFields"),String)
            End Get
            Set
                Me("ExportFields") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Filename4CSV() As String
            Get
                Return CType(Me("Filename4CSV"),String)
            End Get
            Set
                Me("Filename4CSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TrennzeichenCSV() As String
            Get
                Return CType(Me("TrennzeichenCSV"),String)
            End Get
            Set
                Me("TrennzeichenCSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DarstellungszeichenCSV() As String
            Get
                Return CType(Me("DarstellungszeichenCSV"),String)
            End Get
            Set
                Me("DarstellungszeichenCSV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_1() As Boolean
            Get
                Return CType(Me("bOpen_P_1_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_2() As Boolean
            Get
                Return CType(Me("bOpen_P_1_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_3() As Boolean
            Get
                Return CType(Me("bOpen_P_1_3"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_1_4() As Boolean
            Get
                Return CType(Me("bOpen_P_1_4"),Boolean)
            End Get
            Set
                Me("bOpen_P_1_4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_1() As Boolean
            Get
                Return CType(Me("bOpen_P_2_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_2_2() As Boolean
            Get
                Return CType(Me("bOpen_P_2_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_2_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pcc_BerufgruppenSize() As String
            Get
                Return CType(Me("pcc_BerufgruppenSize"),String)
            End Get
            Set
                Me("pcc_BerufgruppenSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pcc_FachbereichSize() As String
            Get
                Return CType(Me("pcc_FachbereichSize"),String)
            End Get
            Set
                Me("pcc_FachbereichSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_3_1() As Boolean
            Get
                Return CType(Me("bOpen_P_3_1"),Boolean)
            End Get
            Set
                Me("bOpen_P_3_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property bOpen_P_3_2() As Boolean
            Get
                Return CType(Me("bOpen_P_3_2"),Boolean)
            End Get
            Set
                Me("bOpen_P_3_2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLVWidth() As Integer
            Get
                Return CType(Me("ifrmLVWidth"),Integer)
            End Get
            Set
                Me("ifrmLVWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLVHeight() As Integer
            Get
                Return CType(Me("ifrmLVHeight"),Integer)
            End Get
            Set
                Me("ifrmLVHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frm_LVLocation() As String
            Get
                Return CType(Me("frm_LVLocation"),String)
            End Get
            Set
                Me("frm_LVLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SortBez() As String
            Get
                Return CType(Me("SortBez"),String)
            End Get
            Set
                Me("SortBez") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_MANr() As String
            Get
                Return CType(Me("bShowColumn_MANr"),String)
            End Get
            Set
                Me("bShowColumn_MANr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeefullname() As String
            Get
                Return CType(Me("bShowColumn_employeefullname"),String)
            End Get
            Set
                Me("bShowColumn_employeefullname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeestreet() As String
            Get
                Return CType(Me("bShowColumn_employeestreet"),String)
            End Get
            Set
                Me("bShowColumn_employeestreet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeeaddress() As String
            Get
                Return CType(Me("bShowColumn_employeeaddress"),String)
            End Get
            Set
                Me("bShowColumn_employeeaddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeepostcode() As String
            Get
                Return CType(Me("bShowColumn_employeepostcode"),String)
            End Get
            Set
                Me("bShowColumn_employeepostcode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeetelefon() As String
            Get
                Return CType(Me("bShowColumn_employeetelefon"),String)
            End Get
            Set
                Me("bShowColumn_employeetelefon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeemobile() As String
            Get
                Return CType(Me("bShowColumn_employeemobile"),String)
            End Get
            Set
                Me("bShowColumn_employeemobile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeequalification() As String
            Get
                Return CType(Me("bShowColumn_employeequalification"),String)
            End Get
            Set
                Me("bShowColumn_employeequalification") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeeemail() As String
            Get
                Return CType(Me("bShowColumn_employeeemail"),String)
            End Get
            Set
                Me("bShowColumn_employeeemail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeebirthday() As String
            Get
                Return CType(Me("bShowColumn_employeebirthday"),String)
            End Get
            Set
                Me("bShowColumn_employeebirthday") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeeahvnumber() As String
            Get
                Return CType(Me("bShowColumn_employeeahvnumber"),String)
            End Get
            Set
                Me("bShowColumn_employeeahvnumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeepermission() As String
            Get
                Return CType(Me("bShowColumn_employeepermission"),String)
            End Get
            Set
                Me("bShowColumn_employeepermission") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeepermissionuntil() As String
            Get
                Return CType(Me("bShowColumn_employeepermissionuntil"),String)
            End Get
            Set
                Me("bShowColumn_employeepermissionuntil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeenationality() As String
            Get
                Return CType(Me("bShowColumn_employeenationality"),String)
            End Get
            Set
                Me("bShowColumn_employeenationality") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeezivilstand() As String
            Get
                Return CType(Me("bShowColumn_employeezivilstand"),String)
            End Get
            Set
                Me("bShowColumn_employeezivilstand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeecanton() As String
            Get
                Return CType(Me("bShowColumn_employeecanton"),String)
            End Get
            Set
                Me("bShowColumn_employeecanton") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeefstate() As String
            Get
                Return CType(Me("bShowColumn_employeefstate"),String)
            End Get
            Set
                Me("bShowColumn_employeefstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeesstate() As String
            Get
                Return CType(Me("bShowColumn_employeesstate"),String)
            End Get
            Set
                Me("bShowColumn_employeesstate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property bShowColumn_employeeadvisor() As String
            Get
                Return CType(Me("bShowColumn_employeeadvisor"),String)
            End Get
            Set
                Me("bShowColumn_employeeadvisor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frmLibraryInfo_Location() As String
            Get
                Return CType(Me("frmLibraryInfo_Location"),String)
            End Get
            Set
                Me("frmLibraryInfo_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLibraryInfoHeight() As Integer
            Get
                Return CType(Me("ifrmLibraryInfoHeight"),Integer)
            End Get
            Set
                Me("ifrmLibraryInfoHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ifrmLibraryInfoWidth() As Integer
            Get
                Return CType(Me("ifrmLibraryInfoWidth"),Integer)
            End Get
            Set
                Me("ifrmLibraryInfoWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property frmLocation_SearchRec() As String
            Get
                Return CType(Me("frmLocation_SearchRec"),String)
            End Get
            Set
                Me("frmLocation_SearchRec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property iSearchRec_Width() As Integer
            Get
                Return CType(Me("iSearchRec_Width"),Integer)
            End Get
            Set
                Me("iSearchRec_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property iSearchRec_Height() As Integer
            Get
                Return CType(Me("iSearchRec_Height"),Integer)
            End Get
            Set
                Me("iSearchRec_Height") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SPMASearch.My.MySettings
            Get
                Return Global.SPMASearch.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
