'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace VacancyService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", ConfigurationName:="VacancyService.SPVakanzDataSoap")>  _
    Public Interface SPVakanzDataSoap
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyTitle", ReplyAction:="*")>  _
        Function ListVacancyTitle(ByVal request As VacancyService.ListVacancyTitleRequest) As VacancyService.ListVacancyTitleResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyRegion", ReplyAction:="*")>  _
        Function ListVacancyRegion(ByVal request As VacancyService.ListVacancyRegionRequest) As VacancyService.ListVacancyRegionResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyBranch", ReplyAction:="*")>  _
        Function ListVacancyBranch(ByVal request As VacancyService.ListVacancyBranchRequest) As VacancyService.ListVacancyBranchResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyCity", ReplyAction:="*")>  _
        Function ListVacancyCity(ByVal request As VacancyService.ListVacancyCityRequest) As VacancyService.ListVacancyCityResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyCanton", ReplyAction:="*")>  _
        Function ListVacancyCanton(ByVal request As VacancyService.ListVacancyCantonRequest) As VacancyService.ListVacancyCantonResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyGroup", ReplyAction:="*")>  _
        Function ListVacancyGroup(ByVal request As VacancyService.ListVacancyGroupRequest) As VacancyService.ListVacancyGroupResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancySubGroup", ReplyAction:="*")>  _
        Function ListVacancySubGroup(ByVal request As VacancyService.ListVacancySubGroupRequest) As VacancyService.ListVacancySubGroupResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancySubGroupA"& _ 
            "ssignedGroup", ReplyAction:="*")>  _
        Function ListVacancySubGroupAssignedGroup(ByVal request As VacancyService.ListVacancySubGroupAssignedGroupRequest) As VacancyService.ListVacancySubGroupAssignedGroupResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancySector", ReplyAction:="*")>  _
        Function ListVacancySector(ByVal request As VacancyService.ListVacancySectorRequest) As VacancyService.ListVacancySectorResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyJobCatego"& _ 
            "ry", ReplyAction:="*")>  _
        Function ListVacancyJobCategory(ByVal request As VacancyService.ListVacancyJobCategoryRequest) As VacancyService.ListVacancyJobCategoryResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyJobDiscip"& _ 
            "lines", ReplyAction:="*")>  _
        Function ListVacancyJobDisciplines(ByVal request As VacancyService.ListVacancyJobDisciplinesRequest) As VacancyService.ListVacancyJobDisciplinesResponse
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname strUserID aus Namespace http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/ListVacancyJobPositi"& _ 
            "ons", ReplyAction:="*")>  _
        Function ListVacancyJobPositions(ByVal request As VacancyService.ListVacancyJobPositionsRequest) As VacancyService.ListVacancyJobPositionsResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyTitleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyTitle", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyTitleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyTitleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyTitleRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyTitleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyTitleResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyTitleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyTitleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyTitleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyTitleResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyTitleResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyTitleResult = ListVacancyTitleResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyRegionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyRegion", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyRegionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyRegionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyRegionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyRegionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyRegionResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyRegionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyRegionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyRegionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyRegionResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyRegionResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyRegionResult = ListVacancyRegionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyBranchRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyBranch", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyBranchRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyBranchRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyBranchRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyBranchResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyBranchResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyBranchResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyBranchResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyBranchResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyBranchResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyBranchResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyBranchResult = ListVacancyBranchResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyCityRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyCity", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyCityRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyCityRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyCityRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyCityResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyCityResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyCityResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyCityResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyCityResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyCityResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyCityResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyCityResult = ListVacancyCityResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyCantonRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyCanton", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyCantonRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyCantonRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyCantonRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyCantonResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyCantonResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyCantonResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyCantonResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyCantonResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyCantonResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyCantonResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyCantonResult = ListVacancyCantonResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyGroupRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyGroup", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyGroupRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyGroupRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyGroupRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyGroupResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyGroupResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyGroupResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyGroupResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyGroupResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyGroupResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyGroupResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyGroupResult = ListVacancyGroupResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySubGroupRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySubGroup", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySubGroupRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySubGroupRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySubGroupRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySubGroupResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySubGroupResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySubGroupResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySubGroupResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySubGroupResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancySubGroupResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancySubGroupResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancySubGroupResult = ListVacancySubGroupResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySubGroupAssignedGroupRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySubGroupAssignedGroup", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySubGroupAssignedGroupRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySubGroupAssignedGroupRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySubGroupAssignedGroupRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public gruppe As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String, ByVal gruppe As String)
            MyBase.New
            Me.strUserID = strUserID
            Me.gruppe = gruppe
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySubGroupAssignedGroupResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySubGroupAssignedGroupResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySubGroupAssignedGroupResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySubGroupAssignedGroupResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySubGroupAssignedGroupResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancySubGroupAssignedGroupResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancySubGroupAssignedGroupResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancySubGroupAssignedGroupResult = ListVacancySubGroupAssignedGroupResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySectorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySector", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySectorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySectorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySectorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancySectorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancySectorResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancySectorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancySectorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancySectorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancySectorResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancySectorResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancySectorResult = ListVacancySectorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobCategoryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobCategory", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobCategoryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobCategoryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobCategoryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String)
            MyBase.New
            Me.strUserID = strUserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobCategoryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobCategoryResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobCategoryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobCategoryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobCategoryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyJobCategoryResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyJobCategoryResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyJobCategoryResult = ListVacancyJobCategoryResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobDisciplinesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobDisciplines", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobDisciplinesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobDisciplinesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobDisciplinesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public JobCategories As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String, ByVal JobCategories As String)
            MyBase.New
            Me.strUserID = strUserID
            Me.JobCategories = JobCategories
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobDisciplinesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobDisciplinesResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobDisciplinesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobDisciplinesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobDisciplinesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyJobDisciplinesResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyJobDisciplinesResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyJobDisciplinesResult = ListVacancyJobDisciplinesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobPositionsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobPositions", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobPositionsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobPositionsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobPositionsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public strUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public JobCategories As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public JobDisciplines As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal strUserID As String, ByVal JobCategories As String, ByVal JobDisciplines As String)
            MyBase.New
            Me.strUserID = strUserID
            Me.JobCategories = JobCategories
            Me.JobDisciplines = JobDisciplines
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListVacancyJobPositionsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListVacancyJobPositionsResponse", [Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/", Order:=0)>  _
        Public Body As VacancyService.ListVacancyJobPositionsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As VacancyService.ListVacancyJobPositionsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://asmx.domain.com/wsSPS_services/SPVacancyData.asmx/")>  _
    Partial Public Class ListVacancyJobPositionsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListVacancyJobPositionsResult As VacancyService.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListVacancyJobPositionsResult As VacancyService.ArrayOfString)
            MyBase.New
            Me.ListVacancyJobPositionsResult = ListVacancyJobPositionsResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SPVakanzDataSoapChannel
        Inherits VacancyService.SPVakanzDataSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SPVakanzDataSoapClient
        Inherits System.ServiceModel.ClientBase(Of VacancyService.SPVakanzDataSoap)
        Implements VacancyService.SPVakanzDataSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyTitle(ByVal request As VacancyService.ListVacancyTitleRequest) As VacancyService.ListVacancyTitleResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyTitle
            Return MyBase.Channel.ListVacancyTitle(request)
        End Function
        
        Public Function ListVacancyTitle(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyTitleRequest = New VacancyService.ListVacancyTitleRequest()
            inValue.Body = New VacancyService.ListVacancyTitleRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyTitleResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyTitle(inValue)
            Return retVal.Body.ListVacancyTitleResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyRegion(ByVal request As VacancyService.ListVacancyRegionRequest) As VacancyService.ListVacancyRegionResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyRegion
            Return MyBase.Channel.ListVacancyRegion(request)
        End Function
        
        Public Function ListVacancyRegion(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyRegionRequest = New VacancyService.ListVacancyRegionRequest()
            inValue.Body = New VacancyService.ListVacancyRegionRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyRegionResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyRegion(inValue)
            Return retVal.Body.ListVacancyRegionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyBranch(ByVal request As VacancyService.ListVacancyBranchRequest) As VacancyService.ListVacancyBranchResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyBranch
            Return MyBase.Channel.ListVacancyBranch(request)
        End Function
        
        Public Function ListVacancyBranch(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyBranchRequest = New VacancyService.ListVacancyBranchRequest()
            inValue.Body = New VacancyService.ListVacancyBranchRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyBranchResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyBranch(inValue)
            Return retVal.Body.ListVacancyBranchResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyCity(ByVal request As VacancyService.ListVacancyCityRequest) As VacancyService.ListVacancyCityResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyCity
            Return MyBase.Channel.ListVacancyCity(request)
        End Function
        
        Public Function ListVacancyCity(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyCityRequest = New VacancyService.ListVacancyCityRequest()
            inValue.Body = New VacancyService.ListVacancyCityRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyCityResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyCity(inValue)
            Return retVal.Body.ListVacancyCityResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyCanton(ByVal request As VacancyService.ListVacancyCantonRequest) As VacancyService.ListVacancyCantonResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyCanton
            Return MyBase.Channel.ListVacancyCanton(request)
        End Function
        
        Public Function ListVacancyCanton(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyCantonRequest = New VacancyService.ListVacancyCantonRequest()
            inValue.Body = New VacancyService.ListVacancyCantonRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyCantonResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyCanton(inValue)
            Return retVal.Body.ListVacancyCantonResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyGroup(ByVal request As VacancyService.ListVacancyGroupRequest) As VacancyService.ListVacancyGroupResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyGroup
            Return MyBase.Channel.ListVacancyGroup(request)
        End Function
        
        Public Function ListVacancyGroup(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyGroupRequest = New VacancyService.ListVacancyGroupRequest()
            inValue.Body = New VacancyService.ListVacancyGroupRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyGroupResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyGroup(inValue)
            Return retVal.Body.ListVacancyGroupResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancySubGroup(ByVal request As VacancyService.ListVacancySubGroupRequest) As VacancyService.ListVacancySubGroupResponse Implements VacancyService.SPVakanzDataSoap.ListVacancySubGroup
            Return MyBase.Channel.ListVacancySubGroup(request)
        End Function
        
        Public Function ListVacancySubGroup(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancySubGroupRequest = New VacancyService.ListVacancySubGroupRequest()
            inValue.Body = New VacancyService.ListVacancySubGroupRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancySubGroupResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancySubGroup(inValue)
            Return retVal.Body.ListVacancySubGroupResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancySubGroupAssignedGroup(ByVal request As VacancyService.ListVacancySubGroupAssignedGroupRequest) As VacancyService.ListVacancySubGroupAssignedGroupResponse Implements VacancyService.SPVakanzDataSoap.ListVacancySubGroupAssignedGroup
            Return MyBase.Channel.ListVacancySubGroupAssignedGroup(request)
        End Function
        
        Public Function ListVacancySubGroupAssignedGroup(ByVal strUserID As String, ByVal gruppe As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancySubGroupAssignedGroupRequest = New VacancyService.ListVacancySubGroupAssignedGroupRequest()
            inValue.Body = New VacancyService.ListVacancySubGroupAssignedGroupRequestBody()
            inValue.Body.strUserID = strUserID
            inValue.Body.gruppe = gruppe
            Dim retVal As VacancyService.ListVacancySubGroupAssignedGroupResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancySubGroupAssignedGroup(inValue)
            Return retVal.Body.ListVacancySubGroupAssignedGroupResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancySector(ByVal request As VacancyService.ListVacancySectorRequest) As VacancyService.ListVacancySectorResponse Implements VacancyService.SPVakanzDataSoap.ListVacancySector
            Return MyBase.Channel.ListVacancySector(request)
        End Function
        
        Public Function ListVacancySector(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancySectorRequest = New VacancyService.ListVacancySectorRequest()
            inValue.Body = New VacancyService.ListVacancySectorRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancySectorResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancySector(inValue)
            Return retVal.Body.ListVacancySectorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyJobCategory(ByVal request As VacancyService.ListVacancyJobCategoryRequest) As VacancyService.ListVacancyJobCategoryResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyJobCategory
            Return MyBase.Channel.ListVacancyJobCategory(request)
        End Function
        
        Public Function ListVacancyJobCategory(ByVal strUserID As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyJobCategoryRequest = New VacancyService.ListVacancyJobCategoryRequest()
            inValue.Body = New VacancyService.ListVacancyJobCategoryRequestBody()
            inValue.Body.strUserID = strUserID
            Dim retVal As VacancyService.ListVacancyJobCategoryResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyJobCategory(inValue)
            Return retVal.Body.ListVacancyJobCategoryResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyJobDisciplines(ByVal request As VacancyService.ListVacancyJobDisciplinesRequest) As VacancyService.ListVacancyJobDisciplinesResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyJobDisciplines
            Return MyBase.Channel.ListVacancyJobDisciplines(request)
        End Function
        
        Public Function ListVacancyJobDisciplines(ByVal strUserID As String, ByVal JobCategories As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyJobDisciplinesRequest = New VacancyService.ListVacancyJobDisciplinesRequest()
            inValue.Body = New VacancyService.ListVacancyJobDisciplinesRequestBody()
            inValue.Body.strUserID = strUserID
            inValue.Body.JobCategories = JobCategories
            Dim retVal As VacancyService.ListVacancyJobDisciplinesResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyJobDisciplines(inValue)
            Return retVal.Body.ListVacancyJobDisciplinesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function VacancyService_SPVakanzDataSoap_ListVacancyJobPositions(ByVal request As VacancyService.ListVacancyJobPositionsRequest) As VacancyService.ListVacancyJobPositionsResponse Implements VacancyService.SPVakanzDataSoap.ListVacancyJobPositions
            Return MyBase.Channel.ListVacancyJobPositions(request)
        End Function
        
        Public Function ListVacancyJobPositions(ByVal strUserID As String, ByVal JobCategories As String, ByVal JobDisciplines As String) As VacancyService.ArrayOfString
            Dim inValue As VacancyService.ListVacancyJobPositionsRequest = New VacancyService.ListVacancyJobPositionsRequest()
            inValue.Body = New VacancyService.ListVacancyJobPositionsRequestBody()
            inValue.Body.strUserID = strUserID
            inValue.Body.JobCategories = JobCategories
            inValue.Body.JobDisciplines = JobDisciplines
            Dim retVal As VacancyService.ListVacancyJobPositionsResponse = CType(Me,VacancyService.SPVakanzDataSoap).ListVacancyJobPositions(inValue)
            Return retVal.Body.ListVacancyJobPositionsResult
        End Function
    End Class
End Namespace
